<?php
/**
 * Copyright © 2016 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */
$isCelebrityPage=false;
$designerPage =false;
$hasChildren =false;
if($this->getRequest()->getFullActionName()=='catalog_category_view'):
$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
$category = $objectManager->get('Magento\Framework\Registry')->registry('current_category');
if($category->hasChildren())
	$hasChildren =true;
if($category->getParentCategory()->getName()=='Designers')
	$designerPage =true;
if($category->getName()=='Celebrity Spotting')
	$isCelebrityPage=true;
endif;

$hide = true;
if($this->getRequest()->getFullActionName()=='catalog_category_view'):
        $genderConfigs = $objectManager->get('Magento\Framework\App\Config\ScopeConfigInterface')->getValue('catalog/custom_filter_gender/custom_filter_gender');
        $onlyAllowedIn = explode(",",$genderConfigs);
                if ($category->getId()):
                                if (in_array($category->getId(), $onlyAllowedIn)){
                                        $hide = false;
                                }
                endif;
endif;

// @codingStandardsIgnoreFile
?>
<?php
/**
 * Category layered navigation
 *
 * @var $block \Magento\LayeredNavigation\Block\Navigation
 */
?>

<?php if ($block->canShowBlock()): ?>
    <div class="block filter" id="layered-filter-block" data-mage-init='{"collapsible":{"openedState": "active", "collapsible": true, "active": false, "collateral": { "openedState": "filter-active", "element": "body" } }}'>
        <?php $filtered = count($block->getLayer()->getState()->getFilters()) ?>
        <div class="block-title filter-title" data-count="<?php /* @escapeNotVerified */ echo $filtered; ?>">
			<strong class="title" data-role="title"><?php /* @escapeNotVerified */ echo __('Select Filter') ?><span class="fa fa-filter"></span></strong>
        </div>
        <div class="block-content filter-content">
            <?php echo $block->getChildHtml('state') ?>

            <?php if ($block->getLayer()->getState()->getFilters()): ?>
                <div class="block-actions filter-actions">
                    <a href="<?php /* @escapeNotVerified */ echo $block->getClearUrl() ?>" class="action btn btn-xs btn-primary clear filter-clear"><span><?php /* @escapeNotVerified */ echo __('Clear All') ?></span></a>
                </div>
            <?php endif; ?>
            <?php $wrapOptions = false; ?>
	    <?php foreach ($block->getFilters() as $filter): ?>
		<?php if($filter->getName()=='Patterns' && $hasChildren ): continue; endif; ?>
		<?php if($filter->getName()=='Gender' && $hide): continue; endif; ?>
                <?php if ($filter->getItemsCount()): ?>
                    <?php if (!$wrapOptions): ?>
                        <strong role="heading" aria-level="2" class="block-subtitle filter-subtitle"><?php /* @escapeNotVerified */ echo __('Filter By') ?></strong>
                        <div class="filter-options" id="narrow-by-list" data-role="content" data-mage-init='{"accordion":{"openedState": "active", "collapsible": true, "active": false, "multipleCollapsible": false}}'>
                    <?php  $wrapOptions = true; endif; ?>
		    <div data-role="collapsible" class="filter-options-item filter-header-<?= strtolower($filter->getName());  ?>">
	               <?php if($filter->getName()=='Category' && $isCelebrityPage ):?>
				     <div data-role="title" class="iscelebrity filter-options-title"><?php /* @escapeNotVerified */ echo __('Celebrity');?></div>
                       <?php elseif($filter->getName()=='Patterns' && !$hasChildren ): ?>
                               <div data-role="title" class="pattern-category filter-options-title"><?php  /* @escapeNotVerified */  echo 'Category'; ?></div>
                       <?php else:?>
                               <div data-role="title" class="default filter-options-title"><?php /* @escapeNotVerified */ echo __($filter->getName());?></div>
                       <?php endif;?>
                        <div data-role="content" class="filter-options-content"><?php /* @escapeNotVerified */ echo $block->getChildBlock('renderer')->render($filter); ?></div>
                    </div>
                <?php endif; ?>
				
            <?php endforeach; ?>
            <?php if ($wrapOptions): ?>
                </div>
            <?php else: ?>
                <script>
                    require([
                        'jquery'
                    ], function ($) {
                        $('#layered-filter-block').addClass('filter-no-options');
                    });
                </script>
            <?php endif; ?>
        </div>
    </div>
<?php endif; ?>
