<?php
 
use Magento\Framework\App\Action\Action;
$product_collection = $block->getRelatedProductsByDesigner();
?>

<div>
    <?php if ($product_collection):?>
    <div class="block widget block-suggested-products grid">
        <div class="block-content">
        <div class="products-grid grid">
            <ol id="pdp_sliderrelated" class="owl-carousel owl-theme">
                
                <?php foreach ($product_collection as $item):
                $_product =$block->getProductById($item->getId());
                ?>
                <li class="product-item-info item">
                <div class="product-top">
                    <?php
                    $image_url = $block->imageHelperObj()->init($_product, 'product_base_image')
                    ->setImageFile($_product->getFile())
                    ->resize($this->getProductimagewidth(),$this->getProductimageheight())
                    ->getUrl();
                    ?>
                    <a href="<?php  echo $_product->getProductUrl() ?>" class="product-item-photo">
                    <img  src="<?php echo  $image_url;?>" alt="<?php echo $this->escapeHtml($_product->getName()) ?>" />
		    </a>
		    <?php if(!$_product->getHideprice()):?>
                    <ul class="actions-link">
                        <?php $quickViewHelper = $this->helper('MGS\QuickView\Helper\Data'); ?>
                        <li class="hidden-sm hidden-xs">
                            <?php echo $quickViewHelper->aroundQuickViewHtml($_product); ?>
                        </li>
                        <li>
                            <button data-title="Add to Wish List" data-post='<?php  echo $this->helper('Magento\Wishlist\Helper\Data')->getAddParams($_product) ?>' class="action towishlist" title="Add to Wish List" role="button">
                                <i class="fa fa-heart"></i>
                            </button>
                        </li>

                        <?php $compareHelper = $this->helper('Magento\Catalog\Helper\Product\Compare'); ?>
                        <li><button data-title="<?php echo $block->escapeHtml(__('Add to Compare')); ?>"
                                    class="action tocompare"
                                    title="<?php echo $block->escapeHtml(__('Add to Compare')); ?>"
                                    aria-label="<?php echo $block->escapeHtml(__('Add to Compare')); ?>"
                                    data-post='<?php /* @escapeNotVerified */ echo $compareHelper->getPostDataParams($_product); ?>'
                                    role="button">
                                <i class="fa fa-retweet"></i>
                            </button></li>
                        <li>
                            <?php $postParams = $block->getAddToCartPostParams($_product); ?>
                            <form data-role="tocart-form" action="<?php /* @escapeNotVerified */ echo $postParams['action']; ?>" method="post">
                                <input type="hidden" name="product" value="<?php /* @escapeNotVerified */ echo $postParams['data']['product']; ?>">
                                <input type="hidden" name="<?php /* @escapeNotVerified */ echo Action::PARAM_NAME_URL_ENCODED; ?>" value="<?php /* @escapeNotVerified */ echo $postParams['data'][Action::PARAM_NAME_URL_ENCODED]; ?>">
                                <?php echo $block->getBlockHtml('formkey')?>
                                <?php $storeManager = \Magento\Framework\App\ObjectManager::getInstance()->get('Magento\Store\Model\StoreManagerInterface'); ?>
                                <button type="submit"
                                        title="<?php echo $block->escapeHtml(__('Add to Cart')); ?>"
                                        class="action tocart ">
                                    <span class="fa fa-shopping-cart"></span>
                                </button>
                            </form>
                        </li>
		    </ul>
		   <?php endif?>	
                    <div class="product-item-details">
                        <strong class="product-item-name">
                        <a title="<?php echo $block->escapeHtml($_product->getName()) ?>"
                        href="<?php echo $_product->getProductUrl() ?>"
                        class="product-item-link">
                            <?php echo $block->escapeHtml($_product->getName()) ?>
                        </a>
                        </strong>
                        <div class="product description product-item-description">
                            <?php echo $block->escapeHtml($_product->getShortDescription()); ?>
                        </div>
                        <?php
                        echo $this->getProductPriceHtml($_product);
			?>

                    </div>
		</div>
		<?php if($_product->getHideprice()): ?>
			<span id="modal-btn" style="padding: 5px 25px; position: relative; top: 8px; border:1px #000 solid;" data-toggle="modal" data-book-id="<?php echo $_product->getSku();?>">Enquire Now</span>
		<?php endif;?>
                </li>
                <?php endforeach ?>
            </ol>
        </div>
        </div>
    </div>
    <?php endif;?>
</div>

<script type="text/javascript">
    require([
        'jquery',
        'mgs/owlcarousel'
    ], function(jQuery){
        (function($) {
            $("#pdp_sliderrelated").owlCarousel({
                items: 4,
                nav: true,
                margin:10,
                dots: false,
                autoplay: false,
                autoplayTimeout:5000,
                autoplayHoverPause:false,
                loop:true,
                navText: ["<i class='fa fa-arrow-left'></i>","<i class='fa fa-arrow-right'></i>"],
                responsive:{
                    0 : {items: 2},
                    480 : {items: 2},
                    768 : {items: 4},
                    980 : {items: 4}
                }
            });
        })(jQuery);
    });
</script>

