<!-- <h1>-------Header----</h1> -->

<script src='<?php echo $block->getViewFileUrl("Fermion_Pagelayout::js/manual_script.js?v=1.68"); ?>'>
</script>	

<h4> Solr Index Products in bulk Using Skus</h4> 

<input type="file" id="files" accept=".csv" file-format="sku"/> 
<button class="submit" id="submit">Upload</button>

<br>-----------------------------------------------------------
<br><br>
<h4> Custum Redirect Url </h4> 

<input type="file" id="refirect-url" accept=".csv" file-format="url"/> 
<button class="submit" id="redirect-submit">Upload</button>

<br>-----------------------------------------------------------
<br><br>

