<?php
/* @var $block \Magento\Framework\View\Element\Template */
?>
<?php
    $cartSummary = $block->getCartSummary();
    $cartSummaryText = $cartSummary == 1 ? __('item') : __('items');
    $utm_url = "?";
    $utm_url_set = false;
    if (isset($_GET['utm_source']) || isset($_GET['utm_medium']) || isset($_GET['utm_campaign']) || isset($_GET['utm_content'])) {
        $params = array();
            
        if (isset($_GET['utm_source']) && !empty($_GET['utm_source'])) {
            $utm_source = rawurlencode($_GET['utm_source']);
            $params[] = "utm_source=" . $utm_source;
        }

        if (isset($_GET['utm_medium']) && !empty($_GET['utm_medium'])) {
            $utm_medium = rawurlencode($_GET['utm_medium']);
            $params[] = "utm_medium=" . $utm_medium;
        }

        if (isset($_GET['utm_campaign']) && !empty($_GET['utm_campaign'])) {
               $utm_campaign = rawurlencode($_GET['utm_campaign']);
            $params[] = "utm_campaign=" . $utm_campaign;
        }

        if (isset($_GET['utm_content']) && !empty($_GET['utm_content'])) {
            $utm_content = rawurlencode($_GET['utm_content']);
            $params[] = "utm_content=" . $utm_content;
        }

        if (!empty($params)) {
            $utm_url .= implode("&", $params);
            $utm_url_set = true;
        }
    }
    $utm_url = $utm_url_set ? $utm_url : '';
?>
    <div class="popup__columns">
        <?php echo $block->getChildHtml('messages') ?>
        <div class="popup__column">
            <div class="popup__column--media">
                <?php echo $block->getChildHtml('product_image') ?>
            </div>
            <div class="popup__column--result">
                <p class="popup__result-title"><?php echo $block->escapeHtml(__('Cart Subtotal')) ?>: <?php /* @noEscape */ echo $block->getCartSubtotal() ?></p>
                <?php if($block->getIsCart()) { ?>
                    <p class="popup__result-view-cart"><a href="javascript:void(0)" data-href="<?php /* @noEscape */ echo $block->getUrl('checkout/cart') ?>"><?php echo $block->escapeHtml(__('View Shopping Cart')) ?></a></p>
                <?php } ?>
            </div>
        </div>
        <div class="popup__actions-wrapper">
                <!-- <button type="button" class="popup__action-close btn btn-default" data-action="continue"><?php //echo $block->escapeHtml(__('Continue Shopping')) ?></button> -->
            <?php if($block->getIsCheckout()) { ?>
                <a class="popup__action-redirect--checkout btn btn-secondary" data-action="redirect-checkout" href="<?php /* @noEscape */ echo $block->getUrl('checkout/cart').$utm_url ?>" data-href="<?php /* @noEscape */ echo $block->getUrl('checkout/cart').$utm_url ?>"><?php echo $block->escapeHtml(__('Review & Checkout')) ?></a>
            <?php } ?>
        </div>
    </div>
<script>
    require(["jquery"], function ($) {
        jQuery(document).ready(function() {
            jQuery('.popup__action-close').click(function(){
                jQuery('.mfp-close').trigger('click');
            });
            jQuery('.popup__result-view-cart').click(function(){
                var url_cart_update = '<?php echo $this->getUrl('ajaxcart/index/updatecart')?>';
                jQuery.ajax({
                    url: url_cart_update,
                    method: "POST"
                });
                window.location.href = jQuery(this).attr('data-href');
            })
            jQuery('.popup__action-redirect--checkout').click(function(){
                var url_cart_update = '<?php echo $this->getUrl('ajaxcart/index/updatecart')?>';
                jQuery.ajax({
                    url: url_cart_update,
                    method: "POST"
                });
                window.location.href = jQuery(this).attr('data-href');
            })
        });

    });
</script>
