<?php

$baseUrl = $block->getBaseUrl(); 
//echo $baseUrl."<br>";
$mediaUrl = $block->getMediaUrl(); 
// echo $mediaUrl;
// die("aaa");

?>
        <footer class="footer">
            <div class="footer-container">
                <div class="middle-footer">
                    <div class="top-footer">
                        <div class="menu-pod">
                            <div class="title">Company</div>
                            <ul class="link-footer">
                                <li><a href="https://aashniandco.com/about">About Us</a></li>
                                <li><a href="https://aashniandco.com/contacts">Customer Care</a></li>
                                <li><a href="https://aashniandco.com/terms-worldwide.html">Terms &amp; conditions for clients outside India</a></li>
                                <li><a href="https://aashniandco.com/terms-within-india.html"> Terms &amp; conditions for clients within India </a></li>
                                <li><a href="https://aashniandco.com/privacy.html"> Privacy and Cookies </a></li>
                             
                            </ul>
                        </div>
                        <div class="menu-pod">
                            <div class="title">Information</div>
                            <ul class="link-footer">
                                <li><a href="https://aashniandco.com/about"> Returns and Exchanges </a></li>
                                <li><a href="https://aashniandco.com/contacts"> Store Policies </a></li>
                                <li><a href="https://aashniandco.com/terms-worldwide.html"> Shipping Options </a></li>
                                <li><a href="https://aashniandco.com/terms-within-india.html"> FAQ's </a></li>
                                <li><a href="https://aashniandco.com/privacy.html">How to Measure</a></li>
                             
                            </ul>
                        </div>
                        <div class="menu-pod">
                            <div class="title"> Social </div>
                            <ul class="link-footer">
                                <li><a href="https://aashniandco.com/about">Facebook</a></li>
                                <li><a href="https://aashniandco.com/contacts"> Twitter</a></li>
                                <li><a href="https://aashniandco.com/terms-worldwide.html"> Instagram</a></li> 
                                <li><a href="https://in.pinterest.com/aashninco/"> Pinterest</a></li>                       
                            </ul>
                        </div>
                        <div class="menu-pod">
                            <div class="title"> STAY IN TOUCH </div>
                            <div class="block newsletter">
                                <div class="content">
                                    <form class="form subscribe" novalidate="novalidate" action="https://aashniandco.com/newsletter/subscriber/new/" method="post" id="newsletter-validate-detail-footer">
                                        <div class="field form-group newsletter">
                                            <div class="control">
                                                <input name="email" type="email" id="newsletter-footer" placeholder="Type your email here" data-validate="{required:true, 'validate-email':true}">
                                            </div>
                                        </div>
                                        <div class="actions">
                                            <button class="action subscribe btn btn-secondary" id="newsletter-button" title="Subscribe" type="submit">
                                                <span>Subscribe</span>
                                            </button>
                                        </div>
                                    </form>
                                </div>
                            </div>
                        </div>
                    </div>                  
                </div>
            </div>

            <div class="copy-right-plot">
                <div class="left-foot"><div class="copy-right">©2022 Aashni + Co</div></div>
                <div class="right-foot">
                    <div class="foot-icon">
                        <ul>
                            <li><a href="#" class="socia-ico fb"><img src=<?php echo $mediaUrl."Homepage/Banner/img/facebook.png"?>></a></li>
                            <li><a href="#" class="socia-ico"><img src=<?php echo $mediaUrl."Homepage/Banner/img/twitter.png"?>></a></li>
                            <li><a href="#" class="socia-ico ista"><img src=<?php echo $mediaUrl."Homepage/Banner/img/instagram.png"?>></a></li>
                             <li><a href="#" class="socia-ico ista"><img src=<?php echo $mediaUrl."Homepage/Banner/img/logos-pinterest.png"?>></a></li>
                        </ul>
                    </div>
                </div>
            </div>
            
            <div class="bottom-footer">
                <div class="container-fluid"> 
                    <!-- <div class="shop-favorite-title">Shop Your Favorites At Aashni & Co</div> -->
                    <p style="font-size: 15px;"><strong>Shop Your Favorites At Aashni & Co</strong></p>
                    <p>Enter the world of luxury fashion with Aashni &amp; Co, which gets you access to the latest designer clothing and accessories. The opulent clothing options present at Aashni &amp; Co London will leave you splendid and mesmerized. With 400+ premium designer collections under one platform, we are a one-stop destination for all your fashion needs, from Indian designer clothes to accessories online. Get your hands on luxury products at our online or London storefront. Featuring a myriad of premier and emerging designers for you on the block, including designer Womenswear, Menswear, Kids Wear, Accessories, Jewelry, Homeware, and Decors for a hassle-free shopping experience. Aashni &amp; Co holds on designer collections by top Indian designers such as Manish Malhotra, Sabyasachi, Anamika Khanna, Anita Dongre, Vvani by Vani Vats, Seema Gujral, Gaurav Gupta, Masaba, Neeta Lulla, Tarun Tahiliani, Ridhi Mehra, Rohit Bal, Shivan &amp; Narresh, and more.</p>
                    <p>Designers on the website offer a wide range of quality products. The product range includes 
                        <a href="https://aashniandco.com/designer">Indian designer wear</a>, 
                        <a href="https://aashniandco.com/men.html"> designer clothing for men</a>, 
                        <a href="https://aashniandco.com/clothing.html">designer clothes for women</a>, 
                        <a href="https://aashniandco.com/accessories/jewelry.html">designer jewelry</a>, 
                        <a href="https://aashniandco.com/homeware.html">Homeware</a> and 
                        <a href="https://aashniandco.com/bridal.html?bridal=6254">bridal trousseau essentials</a>. Designer clothing is available in all categories ranging from 
                        <a href="https://aashniandco.com/women-s-clothing/saris.html">designer Sarees</a>, 
                        <a href="https://aashniandco.com/women-s-clothing/tunics-kurtis.html">Kurtis</a>, 
                        <a href="https://aashniandco.com/women-s-clothing/lehengas.html">Lehengas</a>, 
                        <a href="https://aashniandco.com/men.html?cat=1730">Shirts</a>, 
                        <a href="https://aashniandco.com/men.html?cat=1732">Jackets</a>, 
                        <a href="https://aashniandco.com/men.html?cat=1705">Sherwanis</a>, and more.
                    </p>

                    <p>Shop Indian Designer ensembles and Accessories for every occasion at Aashni &amp; Co. From designer ethnic clothing to indo-western &amp; contemporary wear, we have got you covered with everything to suit your personal style and preferences whether you are looking for casual, formal, semi-formal or occasion wear. You can find perfect Indian designer clothing for every event, whether it is a 
                        <a href="https://aashniandco.com/bridal.html?occasions=6046">Wedding</a>, 
                        <a href="https://aashniandco.com/bridal.html?occasions=6052">Engagement</a>, 
                        <a href="https://aashniandco.com/women-s-clothing/dresses.html">Vacation dresses for women</a>, 
                        <a href="https://aashniandco.com/bridal.html?occasions=6050">Haldi &amp; Mehendi ceremony</a>, 
                        <a href="https://aashniandco.com/bridal.html?bridal=6255&amp;cat=3127">poolside party</a>, destination wedding, 
                        <a href="https://aashniandco.com/bridal.html?cat=3127&amp;occasions=6048">resort wedding</a>, beach wedding, 
                        <a href="https://aashniandco.com/women-s-clothing/anarkalis-kurtas.html?cat=3385%2C3389&amp;occasions=6231">traditional pooja rituals</a>, brunch get-togethers, Black Friday Clothing Deals, Christmas Clothing, and other festive occasions. With so many classy and impeccable couture fashions available at your choice, have the best opportunity to channel your inner desi diva at Indian festivals.</p>

                    <p>We make sure you ace every appearance like a glorious diva, be it your Diwali party, family get-togethers for Eid, groovy Navratri nights, the delightful occasion of Ganesh Chaturthi, Gudi Padwa, Onam, Durga Pooja, Parsi New Year, Christmas, and more. Browse through the ethnic designer collection curated meticulously for men, women &amp; Kids. Shop traditional designer dresses, Sarees, Lehengas, Kurtis for women &amp; girls, Kurtas for men &amp; boys, Sherwanis for men &amp; boys, and more.</p>  

                    <p style="font-size: 15px;"><strong>Shop Exclusive Designer Clothing &amp; Accessories Collection at Aashni &amp; Co</strong></p>

                    <p>Select the finest luxury designers' wear on India's top fashion place- Aashni &amp; Co. Shop for elite Indian designers' collections such as 
                        <a href="https://aashniandco.com/designers/sabyasachi.html">Sabyasachi Mukherjee</a>, 
                        <a href="https://aashniandco.com/designers/manish-malhotra.html">Manish Malhotra</a>, 
                        <a href="https://aashniandco.com/designers/anita-dongre.html">Anita Dongre</a>, 
                        <a href="https://aashniandco.com/designers/fayon-kids-by-preeti-jatia.html">Fayon Kids by Preeti Jatia</a>, 
                        <a href="https://aashniandco.com/designers/masaba.html">Masaba</a>, 
                        <a href="https://aashniandco.com/designers/shivan-narresh.html">Shivan &amp; Narresh</a>, 
                        <a href="https://aashniandco.com/designers/tarun-tahiliani.html">Tarun Tahiliani</a>, 
                        <a href="https://aashniandco.com/designers/joules-by-radhika.html">Joules by Radhika</a>, and more. We offer everything from wedding wear to festive styles, from bridal trousseau to ethnic wear to designer menswear, under one roof. From designer jewellery to accessories with the finest designs and meticulously curated collections are available at Aashni &amp; Co online store as well as at London flagship store!</p>

                    <p>Shop for the latest Indian ethnic designer wear and western clothing by your favorite premium designers.</p>
                    <p style="font-size: 15px;"><strong>Shop Premium Womens Clothing Collection at Aashni &amp; Co</strong></p>

                    <p>At Aashni &amp; Co, you can never go wrong in selecting exquisite outfits, whether you are a bride-to-be, a bridesmaid, a working woman in the corporate world, a mother, a college graduate looking for a job, or simply a stylish diva with a passion for fashion. Our online store offers a wide variety of outfits, from one-of-a-kind runway couture to exclusive 
                        <a href="https://aashniandco.com/clothing.html">designer clothing for women</a> that can easily be part of your wardrobe.</p>

                    <p style="font-size: 15px;"><strong>Let's Explore Celebrity Closet at Aashni &amp; Co</strong></p>

                    <p>Bollywood fashion is now at your fingertips! Pinning fashion inspirations of your favorite celebrity? You can also own them now! Shop ultra-stylish celebrity-spotted looks from our 
                        <a href="https://aashniandco.com/celebrity-spotting.html">Celebrity Closet</a> under one stage at Aashni &amp; Co exclusively. Get the look of your favorite Bollywood diva, whether it is 
                        <a href="https://aashniandco.com/celebrity-spotting/karishma-kapoor.html">Karishma Kapoor</a> or 
                        <a href="https://aashniandco.com/celebrity-spotting/jhanvi-kapoor.html">Janhvi Kapoor</a>, 
                        <a href="https://aashniandco.com/celebrity-spotting/kriti-sanon.html">Kriti Sanon</a> or 
                        <a href="https://aashniandco.com/celebrity-spotting/alia-bhatt.html">Alia Bhatt</a>, 
                        <a href="https://aashniandco.com/celebrity-spotting/kiara-advani.html">Kiara Advani</a> or 
                        <a href="https://aashniandco.com/celebrity-spotting/vidya-balan.html">Vidya Balan</a>, 
                        <a href="https://aashniandco.com/anita-dongre-andf21p62-red-ajrakh-lehenga-set.html">Tara Sutaria</a>, 
                        <a href="https://aashniandco.com/maayera-jaipur-floral-printed-kurta-mrjdtsoct15.html">Salman Khan</a> or Hardik Pandya straight to your closet now. Whether it's a red-carpet look, celebrity wedding attire, an outfit from a movie sequence, a movie premiere, or a promotional appearance, all your loved looks are ready to be part of your wardrobe, winning you the title of fashionista. Check out 
                        <a href="https://aashniandco.com/bridal.html?cat=3133">designer sarees for weddings</a>, 
                        <a href="https://aashniandco.com/women-s-clothing/saris.html?cat=3423">draped saree</a>, 
                        <a href="https://aashniandco.com/women-s-clothing/saris.html?cat=3420">Handwoven Sarees</a>, 
                        <a href="https://aashniandco.com/women-s-clothing/jumpsuits.html">jumpsuits</a>, 
                        <a href="https://aashniandco.com/women-s-clothing/lehengas.html?cat=3391">Classic Lehengas</a>, 
                        <a href="https://aashniandco.com/women-s-clothing/saris.html?cat=3422">pant style saree</a>, 
                        <a href="https://aashniandco.com/women-s-clothing/saris.html?cat=3425">ruffle saree</a>, and more online.
                    </p>

                    <p style="font-size: 15px;">
                        <strong>Keep Up with What Your Favorite Fashion Designer Icons Are up to</strong>
                    </p>

                    <p>The idea of creating an outfit from scratch and showcasing it to a large community of fans via the hashtag has aided individuals in understanding trends and making them suitable for daily wear. Imagine having every item of apparel and jewelry that your favorite fashion icons wear. From Alia Bhatt to Madhuri Dixit Nene, Aashni &amp; Co Journal has a '
                        <a href="https://journal.aashniandco.com/category/fashion-news/">Fashion &amp; News</a>'feature to help track celebrity fashion trends and details of the outfits that are worth exploring. This way, you will never miss out on the 
                        <a href="http://journal.aashniandco.com/">latest Designer fashion trends</a>, from around the world.
                    </p>

                    <p style="font-size: 15px;"><strong>New Product Launches and Trending Topics Updates</strong></p>

                    <p>Since fashion seems extremely hard to keep up with these days, a quick update on what is trending in accessories, clothing, and footwear would undoubtedly be of great help.</p>

                    <p>
                        <a href="http://journal.aashniandco.com/">Aashni &amp; Co’ Journal</a> helps you stay connected to the most beloved and sought-after fashion designers such as 
                        <a href="https://aashniandco.com/designers/manish-malhotra.html">Manish Malhotra</a>, 
                        <a href="https://aashniandco.com/designers/sabyasachi.html">Sabyasachi Mukherjee</a>, 
                        <a href="https://aashniandco.com/designers/tarun-tahiliani.html">Tarun Tahiliani</a>, 
                        <a href="https://aashniandco.com/designers/suhani-pittie.html">Suhani Pittie</a>, and many more. Join us on our social media platforms and stay updated with stories of designer curations related to clothing, footwear, and jewellery, along with their new seasonal collections.</p>

                    <p>
                        <a href="https://www.instagram.com/aashniandco/"> Instagram </a>|
                        <a href="https://www.facebook.com/pages/Aashni-Co-Official/417895134941609"> Facebook </a>|<a href="https://twitter.com/aashniuk"> Twitter </a>
                    </p>

                    <p style="font-size: 15px;"><strong>Explore Aashni &amp; Co's Luxury Clothing</strong></p>
                    <p style="font-size: 15px;"><strong>Top Designers for Clothing</strong></p>

                    <p>
                        <a href="https://aashniandco.com/designers/sabyasachi.html">
                            <u class="bold_text">Sabyasachi Mukherjee </u>
                        </a>|
                        <a href="https://aashniandco.com/designers/tarun-tahiliani.html">
                            <u class="bold_text"> Tarun Tahiliani</u> 
                        </a>|
                        <a href="https://aashniandco.com/designers/gulabo-by-abu-sandeep.html"><u class="bold_text"> Abu Jani and Sandeep Khosla </u></a>|<a href="https://aashniandco.com/designers/anamika-khanna.html"><u class="bold_text"> Anamika Khanna </u></a>|
                        <a href="https://aashniandco.com/designers/anita-dongre.html"> <u class="bold_text">Anita Dongre </u></a>|
                        <a href="https://aashniandco.com/designers/manish-malhotra.html"> <u class="bold_text">Manish Malhotra </u></a>|
                        <a href="https://aashniandco.com/designers/amit-aggarwal.html"> <u class="bold_text">Amit Aggarwal </u></a>|
                        <a href="https://aashniandco.com/designers/anushree-reddy.html"> <u class="bold_text">Anushree Reddy </u></a>|
                        <a href="https://aashniandco.com/designers/seema-gujral.html"> <u class="bold_text">Seema Gujral </u></a>|
                        <a href="https://aashniandco.com/designers/rohit-bal.html"> <u class="bold_text"><u class="bold_text">Rohit Bal </u></u></a>|
                        <a href="https://aashniandco.com/designers/varun-bahl.html"><u class="bold_text"> Varun Bahl </u></a>|
                        <a href="https://aashniandco.com/designers/house-of-torani.html"><u class="bold_text"> Torani </u></a>|
                        <a href="https://aashniandco.com/designers/ritu-kumar.html"><u class="bold_text"> Ritu Kumar </u></a>|
                        <a href="https://aashniandco.com/designers/jayanti-reddy.html"><u class="bold_text"> Jayanti Reddy </u></a>|<a href="https://aashniandco.com/designers/ridhi-mehra.html"><u class="bold_text"> Ridhi Mehra </u></a>|
                        <a href="https://aashniandco.com/designers/rohit-gandhi-rahul-khanna.html"><u class="bold_text">Rohit Gandhi + Rahul Khanna </u> </a>|
                        <a href="https://aashniandco.com/designers/aisha-rao.html"><u class="bold_text"> Aisha Rao </u></a>|
                        <a href="https://aashniandco.com/designers/abhinav-mishra.html"><u class="bold_text">Abhinav Mishra</u> </a>|
                        <a href="https://aashniandco.com/designers/punit-balana.html"><u class="bold_text">Punit Balana </u> </a>|
                        <a href="https://aashniandco.com/designers/jade-by-monica-and-karishma.html"><u class="bold_text"> Jade By Monica and Karishma </u></a>|
                        <a href="https://aashniandco.com/designers/masaba.html"><u class="bold_text"> Masaba </u></a>|
                        <a href="https://aashniandco.com/designers/ak-ok.html"><u class="bold_text"> AK-OK </u></a>|
                        <a href="https://aashniandco.com/designers/payal-singhal.html"><u class="bold_text"> Payal Singhal </u></a>|
                        <a href="https://aashniandco.com/designers/mishru.html"><u class="bold_text"> Mishru </u></a>|
                        <a href="https://aashniandco.com/designers/ridhima-bhasin.html"><u class="bold_text"> Ridhima Bhasin </u></a>|
                        <a href="https://aashniandco.com/designers/vvani-by-vani-vats.html"><u class="bold_text"> Vvani by Vani Vats </u></a>|
                        <a href="https://aashniandco.com/designers/ritika-mirchandani.html"><u class="bold_text"> Ritika Mirchandani </u></a>|
                        <a href="https://aashniandco.com/designers/sva-sonam-and-paras-modi.html"><u class="bold_text"> SVA / Sonam and Paras Modi </u></a>|
                        <a href="https://aashniandco.com/designers/mrunalini-rao.html"><u class="bold_text"> Mrunalini Rao </u></a>|
                        <a href="https://aashniandco.com/designers/shivan-narresh.html"><u class="bold_text"> Shivan &amp; Narresh </u></a>|
                        <a href="https://aashniandco.com/designers/not-so-serious-by-pallavi-mohan.html"><u class="bold_text"> Not So Serious by Pallavi Mohan </u></a>|
                        <a href="https://aashniandco.com/designers/rajdeep-ranawat.html"><u class="bold_text"> Rajdeep Ranawat </u></a>|<a href="https://aashniandco.com/designers/aneesh-agarwaal.html"><u class="bold_text"> Aneesh Agarwaal </u></a>|
                        <a href="https://aashniandco.com/designers/bhumika-sharma.html"><u class="bold_text"> Bhumika Sharma </u></a>|
                        <a href="https://aashniandco.com/designers/sukriti-akriti.html"><u class="bold_text"> Sukriti &amp; Aakriti </u></a>|<a href="https://aashniandco.com/designers/mahima-mahajan.html"><u class="bold_text"> Mahima Mahajan </u></a>|
                        <a href="https://aashniandco.com/designers/saaksha-kinni.html"><u class="bold_text"> Saaksha &amp; Kinni </u></a>|
                        <a href="https://aashniandco.com/designers/431-88-by-shweta-kapur.html"><u class="bold_text"> 431-88 by Shweta Kapur </u></a>|
                        <a href="https://aashniandco.com/designers/431-88-by-shweta-kapur.html"><u class="bold_text"> 431-88 by Shweta Kapur </u></a>|
                        <a href="https://aashniandco.com/designers/archana-jaju.html"><u class="bold_text"> Archana Jaju </u></a>|<a href="https://aashniandco.com/designers/astha-narang.html"><u class="bold_text"> Astha Narang </u></a>|
                        <a href="https://aashniandco.com/designers/siddartha-tytler.html"><u class="bold_text"> Siddartha Tytler </u></a>|<a href="https://aashniandco.com/designers/gopi-vaid.html"><u class="bold_text"> Gopi Vaid </u></a>|
                        <a href="https://aashniandco.com/designers/shyam-narayan-prasad.html"><u class="bold_text"> Shyam Narayan Prasad </u></a>|
                        <a href="https://aashniandco.com/designers/just-shradha-s.html"><u class="bold_text"> Just Shradha's </u></a>|
                        <a href="https://aashniandco.com/designers/just-jewellery.html"><u class="bold_text"> Just Jewelry </u></a>|
                        <a href="https://aashniandco.com/designers/moh-maya-by-disha-khatri.html"><u class="bold_text"> Moh-Maya by Disha Khatri </u></a>|
                        <a href="https://aashniandco.com/designers/ritika-sachdeva.html"><u class="bold_text"> Ritika Sachdeva </u></a></p>

                        <p style="font-size: 15px;"><strong>Top Categories in Women’s Clothing</strong></p>

                        <p>
                            <a href="https://aashniandco.com/women-s-clothing/lehengas.html"><u class="bold_text">Lehenga </u></a>|
                            <a href="https://aashniandco.com/women-s-clothing/dresses.html"><u class="bold_text"> Dresses </u></a>|<a href="https://aashniandco.com/women-s-clothing/saris.html"><u class="bold_text"> Saree </u></a>|
                            <a href="https://aashniandco.com/women-s-clothing/jumpsuits.html"><u class="bold_text"> Jumpsuits </u></a>|
                            <a href="https://aashniandco.com/women-s-clothing/anarkalis-kurtas.html?cat=3385%2C3389"><u class="bold_text"><u class="bold_text"> Kurtas </u></u></a>|
                            <a href="https://aashniandco.com/women-s-clothing/tunics-kurtis.html"><u class="bold_text"> Tunics &amp; Kurtis </u></a>|
                            <a href="https://aashniandco.com/women-s-clothing/anarkalis-kurtas.html"><u class="bold_text"> Anarkalis </u></a>|
                            <a href="https://aashniandco.com/women-s-clothing/gowns.html"><u class="bold_text"> Gowns </u></a>|
                            <a href="https://aashniandco.com/clothing/kaftans.html"><u class="bold_text"> Kaftans </u></a>|
                            <a href="https://aashniandco.com/women-s-clothing/tops.html"><u class="bold_text"> Tops </u></a>|
                            <a href="https://aashniandco.com/women-s-clothing/pants.html"><u class="bold_text"> Pants </u></a>|
                            <a href="https://aashniandco.com/women-s-clothing/skirts.html"><u class="bold_text"> Skirts </u></a>|<a href="https://aashniandco.com/women-s-clothing/co-ords.html"><u class="bold_text"> Co-ords </u></a>|
                            <a href="https://aashniandco.com/women-s-clothing/jackets-and-capes.html"><u class="bold_text"> Jackets &amp; Capes </u></a>|
                            <a href="https://aashniandco.com/women-s-clothing/beach.html"><u class="bold_text"> Beachwear </u></a>|
                            <a href="https://aashniandco.com/clothing/loungewear.html"><u class="bold_text"> Loungewear </u></a>|
                            <a href="https://aashniandco.com/women-s-clothing/anarkalis-kurtas.html?cat=3388"><u class="bold_text"> Shararas </u></a>
                        </p>

                        <p style="font-size: 15px;"><strong>Top Categories in Men’s Clothing</strong></p>
                        <p>
                            <a href="https://aashniandco.com/men.html?cat=1732"><u class="bold_text">Jackets</u></a>|
                            <a href="https://aashniandco.com/men.html?cat=1730"><u class="bold_text"> Shirts </u></a>|
                            <a href="https://aashniandco.com/men.html?cat=1705"><u class="bold_text"> Sherwanis </u></a>|
                            <a href="https://aashniandco.com/men.html?cat=1704"><u class="bold_text"> Bandi </u></a>|
                            <a href="https://aashniandco.com/men.html?cat=3048"><u class="bold_text"> Bandi Sets </u></a>|
                            <a href="https://aashniandco.com/men.html?edits=6228"><u class="bold_text"> Nehru Jacket </u></a>|
                            <a href="https://aashniandco.com/men.html?cat=3173"><u class="bold_text"> Bandhgalas </u></a>|
                            <a href="https://aashniandco.com/men.html?cat=1703"><u class="bold_text"> Kurta Sets </u></a>
                        </p>
                        <p style="font-size: 15px;"><strong>Top Categories in Kids Clothing</strong></p>
                        <p>
                            <a href="https://aashniandco.com/kids-wear.html?cat=3324"><u class="bold_text">Kurtas For Girls </u></a>|
                            <a href="https://aashniandco.com/kids-wear.html?cat=2135"><u class="bold_text"> Lehengas For Girls </u></a>|
                            <a href="https://aashniandco.com/kids-wear.html?cat=2137"><u class="bold_text"> Anarkalis For Girls </u></a>|
                            <a href="https://aashniandco.com/kids-wear.html?cat=2138"><u class="bold_text"> Palazzo Sets For Girls </u></a>|
                            <a href="https://aashniandco.com/kids-wear.html?cat=2144"><u class="bold_text"> Sherwanis For Boys </u></a>|
                            <a href="https://aashniandco.com/kids-wear.html?cat=3328"><u class="bold_text"> Kurtas For Boys </u></a>|
                            <a href="https://aashniandco.com/kids-wear.html?cat=2142"><u class="bold_text"> Bandi Sets For Boys</u></a>
                        </p>

                        <p style="font-size: 15px;"><strong>Designer wear for all your Special Occasions</strong></p>

                        <p>
                            <a href="https://aashniandco.com/bridal.html?occasions=6050"><u class="bold_text">Haldi &amp; Mehndi </u></a>|
                            <a href="https://aashniandco.com/bridal.html?occasions=6052"><u class="bold_text"> Engagement </u></a>|
                            <a href="https://aashniandco.com/bridal.html?occasions=6053"><u class="bold_text"> Cocktail </u></a>|
                            <a href="https://aashniandco.com/bridal.html?occasions=6046"><u class="bold_text"> Wedding </u></a>|
                            <a href="https://aashniandco.com/bridal.html?occasions=6049"><u class="bold_text"> Reception </u></a>|
                            <a href="https://aashniandco.com/generic/black-friday-sale.html"><u class="bold_text"> Black Friday </u></a> | Christmas
                        </p>

                        <p style="font-size: 15px;"><strong>Top Designer Accessories For</strong></p>

                        <p>
                            <a href="https://aashniandco.com/accessories.html"><u class="bold_text">Accessories For Women </u></a>|
                            <a href="https://aashniandco.com/men/mens-accessories.html"> <u class="bold_text">Accessories For Men </u></a>|
                            <a href="https://aashniandco.com/kids-wear/kids-accessories.html"><u class="bold_text"> Accessories For Kids </u></a>
                        </p>

                        <p style="font-size: 15px;"><strong>Best Designer Homeware Accessories</strong></p>
                        <p>
                            <a href="https://aashniandco.com/homeware.html?cat=2011"><u class="bold_text">Decorative Accessories </u></a>|
                            <a href="https://aashniandco.com/homeware.html?cat=2012"><u class="bold_text"> Bedding Elements </u></a>|
                            <a href="https://aashniandco.com/homeware.html?cat=2010"><u class="bold_text"> Dinnerware </u></a>
                        </p>

                        <p style="font-size: 15px;"><strong>Check Out Aashni &amp; Co’s Special Edits</strong></p>
                        <p>
                            <a href="https://aashniandco.com/clothing.html?edits=6219"><u class="bold_text">Cult Finds </u></a>|
                            <a href="https://aashniandco.com/clothing.html?edits=6210"><u class="bold_text"> Kurtas Under $200 </u></a>|
                            <a href="https://aashniandco.com/celebrity-spotting.html"><u class="bold_text"> Celebrity Spotting </u></a>|
                            <a href="https://aashniandco.com/clothing.html?edits=6222"><u class="bold_text"> Everyday Staples </u></a>|
                            <a href="https://aashniandco.com/clothing.html?edits=6209"><u class="bold_text"> Sustainable Fashion </u></a>|
                            <a href="https://aashniandco.com/clothing.html?deliverytimes=6038"><u class="bold_text"> Ready To Ship </u></a>|
                            <a href="https://aashniandco.com/clothing.html?edits=6208"><u class="bold_text"> Exclusives </u></a>|
                            <a href="https://aashniandco.com/men.html?edits=6218"><u class="bold_text"> Off The Runway </u></a>|
                            <a href="https://aashniandco.com/bridal.html?bridal=6252"><u class="bold_text"> Heritage Weaves </u></a>|
                            <a href="https://aashniandco.com/bridal.html?bridal=6253"><u class="bold_text"> Lehengas Under $2000 </u></a>|
                            <a href="https://aashniandco.com/bridal.html?bridal=6254"><u class="bold_text"> Trousseau Essentials </u></a>|
                            <a href="https://aashniandco.com/bridal.html?bridal=6262"><u class="bold_text"> Finishing Touches </u></a>|
                            <a href="https://aashniandco.com/kids-wear.html?edits=6229"><u class="bold_text"> Floral Edit </u></a>|
                            <a href="https://aashniandco.com/homeware.html?edits=6215"><u class="bold_text"> Best Sellers </u></a>|
                            <a href="https://aashniandco.com/homeware.html?edits=6216"><u class="bold_text"> Housewarming Gifts </u></a>|
                            <a href="https://aashniandco.com/anniversary-2022"><u class="bold_text"> Sale </u></a>
                        </p>

                        <p style="font-size: 15px;"><strong>We Ship Internationally</strong></p>

                        <p>United Kingdom (UK) | United States of America (USA) | India | Germany | Australia | Canada | Japan | Argentina | Malaysia | Madagascar | Mexico | Morocco | Nepal | Russia | Saudi Arabia | Singapore | South Africa | Sri Lanka | Switzerland | Thailand | United Arab Emirates(UAE) | Vietnam &amp; many other countries</p>




                </div>
            </div>

        </footer> 

</body>
 <!-- <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.6.1/jquery.min.js" integrity="sha512-aVKKRRi/Q/YV+4mjoKBsE4x3H+BkegoM/em46NNlCqNTmUYADjBbeNefNxYV7giUp0VxICtqdrbqU7iVaeZNXA==" crossorigin="anonymous" referrerpolicy="no-referrer"></script> 
 <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.2/jquery.min.js"></script>  
<script type="text/javascript" src='<?php //echo $baseUrl."pub/static/frontend/Mgs/ethan/en_US/Fermion_Pagelayout/js/jquery-3.3.1.min.js"?>'></script>
 <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.6.1/jquery.min.js" integrity="sha512-aVKKRRi/Q/YV+4mjoKBsE4x3H+BkegoM/em46NNlCqNTmUYADjBbeNefNxYV7giUp0VxICtqdrbqU7iVaeZNXA==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>   -->
 <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.1/jquery.min.js"></script>
<script type="text/javascript" src='<?php echo $baseUrl."pub/static/frontend/Mgs/ethan/en_US/Fermion_Pagelayout/js/slick.js"?>'></script>
<script type="text/javascript" src="<?php echo $baseUrl;?>pub/static/frontend/Mgs/ethan/en_US/Fermion_Pagelayout/js/header.js"></script>
<script type="text/javascript" src='<?php echo $baseUrl."pub/static/frontend/Mgs/ethan/en_US/Fermion_Pagelayout/js/home.js"?>'></script>  
</html>