<?php

$baseUrl = $block->getBaseUrl(); 
echo $baseUrl."<br>";
//die("bbb");
$mediaUrl = $block->getMediaUrl(); 
//echo $mediaUrl;
//die("aaa");
// echo $mediaUrl.'Homepage/Banner/img/aashni_banner.jpg';
// die();
?>

    <div class="wrap">

        <div class="subscribe-text">
            <img src="pub/media/wysiwyg/homepage/28-11-22/MicrosoftTeams-image_(1).png" class="alert-msg">
            <span>Thia email address is already subscribed</span>
        </div>
        <div class="banner-block">
            <div class="home-next">
                 <img src="<?php echo $mediaUrl;?>Homepage/Banner/img/right-arrow.svg">
            </div>                       
            <div class="home-previous">
                <img src="<?php echo $mediaUrl;?>Homepage/Banner/img/left-arrow.svg">
            </div>
            <div class="banner-slider">
                <div class="banner-blog">
                    <a href="designers/seema-gujral.html"><img src=<?php echo $mediaUrl."wysiwyg/homepage/28-11-22/Final-Part-2.jpg"?>></a></div>
                <div class="banner-blog">
                    <a href="designers/mahima-mahajan.html"><img src=<?php echo $mediaUrl."wysiwyg/homepage/28-11-22/Final-Part-1.jpg"?>></a></div>
                <div class="banner-blog">
                    <a href="designers/ridhima-bhasin.html"><img src=<?php echo $mediaUrl."wysiwyg/homepage/28-11-22/Final-Part-3.jpg"?>></a></div>
                <div class="banner-blog">
                    <a href="designers/tarun-tahiliani.html"><img src=<?php echo $mediaUrl."wysiwyg/homepage/28-11-22/Final-Part-4.jpg"?>></a></div>
            </div>
        </div>

        <div class="discovery-newly-block">
            <a href="new-in.html?calender=6204"><img src="<?php echo $mediaUrl;?>wysiwyg/homepage/06-07-22/aashni_banner.jpg"></a>
        </div>

        <div class="new-in-block">
            <div class="newin-patch"><img src="<?php echo $mediaUrl;?>wysiwyg/homepage/02-12-21/new_in2.png"></div>
            <div class="newin-img-plot">
                <div class="newin-next">
                    <img src="<?php echo $mediaUrl;?>Homepage/Banner/img/right-arrow.svg">
                </div>                      
                <div class="newin-previous">
                    <img src="<?php echo $mediaUrl;?>Homepage/Banner/img/left-arrow.svg">
                </div>

                <div class="newin-slider">
                    <div class="owl-item">
                        <a href="designers/charkhee.html"><img src="<?php echo $mediaUrl;?>wysiwyg/homepage/28-11-22/Final-Part-13.jpg"></a>
                    </div>
                    <div class="owl-item">
                        <a href="designers/gulabo-by-abu-sandeep.html"><img src="<?php echo $mediaUrl;?>wysiwyg/homepage/28-11-22/Final-Part-14.jpg"></a>
                    </div>
                    <div class="owl-item">
                        <a href="designers/nupur-kanoi.html"><img src="<?php echo $mediaUrl;?>wysiwyg/homepage/28-11-22/Final-Part-15.jpg"></a>
                    </div>
                    <div class="owl-item">
                        <a href="designers/kinjal-modi.html.html"><img src="<?php echo $mediaUrl;?>wysiwyg/homepage/28-11-22/Final-Part-16.jpg"></a>
                    </div>
                    <div class="owl-item">
                        <a href="designers/shivan-narresh.html"><img src="<?php echo $mediaUrl;?>wysiwyg/homepage/28-11-22/Final-Part-17.jpg"></a>
                    </div>
                    <div class="owl-item">
                        <a href="designers/saksham-neharicka.html"><img src="<?php echo $mediaUrl;?>wysiwyg/homepage/28-11-22/Final-Part-10.jpg"></a>
                    </div>
                    <div class="owl-item">
                        <a href="designers/awigna.html.html"><img src="<?php echo $mediaUrl;?>wysiwyg/homepage/28-11-22/Final-Part-11.jpg"></a>
                    </div>
                    <div class="owl-item">
                        <a href="designers/kalista.html.html"><img src="<?php echo $mediaUrl;?>wysiwyg/homepage/28-11-22/Final-Part-12.jpg"></a>
                    </div>
                    <div class="owl-item">
                        <a href="designers/house-of-torani.html"><img src="<?php echo $mediaUrl;?>wysiwyg/homepage/28-11-22/Final-Part-05.jpg"></a>
                    </div>
                    <div class="owl-item">
                        <a href="designers/sana-barreja.html"><img src="<?php echo $mediaUrl;?>wysiwyg/homepage/28-11-22/Final-Part-06.jpg"></a>
                    </div>
                    <div class="owl-item">
                        <a href="designers/ritu-kumar.html"><img src="<?php echo $mediaUrl;?>wysiwyg/homepage/28-11-22/Final-Part-07.jpg"></a>
                    </div>
                    <div class="owl-item">
                        <a href="designers/ritika-mirchandani.html"><img src="<?php echo $mediaUrl;?>wysiwyg/homepage/28-11-22/Final-Part-08.jpg"></a>
                    </div>
                    <div class="owl-item">
                        <a href="designers/prints-by-radhika.html.html"><img src="<?php echo $mediaUrl;?>wysiwyg/homepage/28-11-22/Final-Part-09.jpg"></a>
                    </div>
                </div>
            </div>
        </div>

        <div class="occassion-dress">
            <div class="occasion-img">
                <a href="new-in.html?firstAttemptedFilter=acoeditFilter&amp;acoeditFilter=6224"><img src="<?php echo $mediaUrl;?>wysiwyg/homepage/28-11-22/Final-Part-18.jpg"></a>
            </div>
            <div class="occasion-img">
                <a href="designers/sabyasachi.html?utm_medium=hp-10mar-sabyasachi&amp;utm_source=hp"><img src="<?php echo $mediaUrl;?>wysiwyg/homepage/28-11-22/Final-Part-19.jpg"></a>
            </div>
            <div class="occasion-img">
                <a href="clothing.html?firstAttemptedFilter=acoeditFilter&amp;acoeditFilter=6225"><img src="<?php echo $mediaUrl;?>wysiwyg/homepage/28-11-22/Final-Part-20.jpg"></a>
            </div>
        </div>

        <div class="content-heading">
            <h3 class="title"><img src="<?php echo $mediaUrl;?>wysiwyg/a_co_edit.png" alt=""></h3>
        </div>

        <div class="a-co-edits">
            <div class="co-edit-block">
                <div class="co-edi-next">
                    <img src="<?php echo $mediaUrl;?>Homepage/Banner/img/right-arrow.svg">
                </div>                     
                <div class="co-edi-previous">
                     <img src="<?php echo $mediaUrl;?>Homepage/Banner/img/left-arrow.svg">
                </div>

                <div class="a-coedit-slider">
                    <div class="a-co-item">
                        <a href="clothing.html?firstAttemptedFilter=acoeditFilter&amp;acoeditFilter=6222"><img src="<?php echo $mediaUrl;?>wysiwyg/homepage/28-11-22/Final-Part-21.jpg"></a>
                    </div>
                    <div class="a-co-item">
                        <a href="clothing.html?firstAttemptedFilter=acoeditFilter&amp;acoeditFilter=6210"><img src="<?php echo $mediaUrl;?>wysiwyg/homepage/28-11-22/Final-Part-22.jpg"></a>
                    </div>
                    <div class="a-co-item">
                        <a href="men.html?firstAttemptedFilter=acoeditFilter&amp;acoeditFilter=6219"><img src="<?php echo $mediaUrl;?>wysiwyg/homepage/28-11-22/Final-Part-23.jpg"></a>
                    </div>
                    <div class="a-co-item">
                        <a href="new-in/clothing/sarees.html?firstAttemptedFilter=categoryFilter&amp;categoryFilter=3103"><img src="<?php echo $mediaUrl;?>wysiwyg/homepage/28-11-22/Final-Part-24.jpg"></a>
                    </div>
                    <div class="a-co-item">
                        <a href="accessories.html?firstAttemptedFilter=acoeditFilter&amp;acoeditFilter=6367"><img src="<?php echo $mediaUrl;?>wysiwyg/homepage/28-11-22/Final-Part-25.jpg"></a>
                    </div>
                    <div class="a-co-item">
                        <a href="accessories.html?firstAttemptedFilter=acoeditFilter&amp;acoeditFilter=6211"><img src="<?php echo $mediaUrl;?>wysiwyg/homepage/28-11-22/Final-Part-26.jpg"></a>
                    </div>
                    <div class="a-co-item">
                        <a href="women-s-clothing/lehengas.html?firstAttemptedFilter=categoryFilter&amp;categoryFilter=3396"><img src="<?php echo $mediaUrl;?>wysiwyg/homepage/28-11-22/Final-Part-27.jpg"></a>
                    </div>
                    
                </div>
            </div>
        </div>

        <div class="content-heading">
            <h3 class="title shop-style"><img src="<?php echo $mediaUrl;?>wysiwyg/homepage/02-12-21/shop_by_style.jpg" alt=""></h3>
        </div>

        <div class="shop-by-style-block">
            <div class="style-plot">
                <div class="style-item">
                    <a href="women-s-clothing/anarkalis-kurtas.html?firstAttemptedFilter=categoryFilter&amp;categoryFilter=3388"><img src="<?php echo $mediaUrl;?>wysiwyg/homepage/28-11-22/Final-Part-28.jpg"></a>
                </div>
                <div class="style-item">
                    <a href="women-s-clothing/saris.html?utm_medium=hp-25jan-style-saris&amp;utm_source=hp"><img src="<?php echo $mediaUrl;?>wysiwyg/homepage/28-11-22/Final-Part-29.jpg"></a>
                </div>
                <div class="style-item">
                    <a href="women-s-clothing/anarkalis-kurtas.html?firstAttemptedFilter=categoryFilter&amp;categoryFilter=3380"><img src="<?php echo $mediaUrl;?>wysiwyg/homepage/28-11-22/Final-Part-30.jpg"></a>
                </div>
                <div class="style-item">
                    <a href="women-s-clothing/lehengas.html"><img src="<?php echo $mediaUrl;?>wysiwyg/homepage/28-11-22/Final-Part-30_1.jpg"></a>
                </div>
                <div class="style-item">
                    <a href="new-in.html?firstAttemptedFilter=categoryFilter&amp;categoryFilter=4046"><img src="<?php echo $mediaUrl;?>wysiwyg/homepage/28-11-22/Final-Part-30_2.jpg"></a>
                </div>
                <div class="style-item">
                    <a href="women-s-clothing/co-ords.html"><img src="<?php echo $mediaUrl;?>wysiwyg/homepage/28-11-22/Final-Part-30_3.jpg"></a>
                </div>
            </div>
        </div>

        <div class="bride-styling">
            <div class="bride-plot">
                <div class="wed-item">
                    <a href="bridal"><img src="<?php echo $mediaUrl;?>wysiwyg/homepage/28-11-22/Final-Part-31.jpg"></a>
                </div>
                <div class="wed-item wed-items">
                    <a href="celebrity-spotting.html?utm_medium=hp-10mar-celebrity-spotting&amp;utm_source=hp"><img src="<?php echo $mediaUrl;?>wysiwyg/homepage/28-11-22/Final-Part-32.jpg"></a>
                </div>
            </div>
        </div>

        <div class="content-heading">
            <h3 class="title shop-style"><img src="<?php echo $mediaUrl;?>wysiwyg/homepage/02-12-21/accessory_edit.jpg" alt=""></h3>
        </div>

        <div class="accessory-edits">
            <div class="accessory-block">
                <!-- <div class="access-next"></div>                        
                <div class="access-previous"></div> -->

                <div class="access-slider">
                    <div class="access-item">
                        <a href="designers/shlok-jewels.html"><img src="<?php echo $mediaUrl;?>wysiwyg/homepage/28-11-22/Final-Part-33.jpg"></a>
                    </div>
                    <div class="access-item">
                        <a href="designers/outhouse.html"><img src="<?php echo $mediaUrl;?>wysiwyg/homepage/28-11-22/Final-Part-34.jpg"></a>
                    </div>
                    <div class="access-item">
                        <a href="designers/joules-by-radhika.html"><img src="<?php echo $mediaUrl;?>wysiwyg/homepage/28-11-22/Final-Part-35.jpg"></a>
                    </div>
                    <div class="access-item">
                        <a href="designers/crimzon-world.html"><img src="<?php echo $mediaUrl;?>wysiwyg/homepage/28-11-22/Final-Part-36.jpg"></a>
                    </div>
                    <div class="access-item">
                        <a href="designers/zevar-by-geeta.html"><img src="<?php echo $mediaUrl;?>wysiwyg/homepage/28-11-22/Final-Part-37.jpg"></a>
                    </div>
                    <div class="access-item">
                        <a href="designers/modello-domani.html"><img src="<?php echo $mediaUrl;?>wysiwyg/homepage/28-11-22/Final-Part-38.jpg"></a>
                    </div>
                    
                </div>
            </div>
        </div>

        <div class="styling-block">
            <div class="styling-plot">
                <div class="style-item">
                    <a href="men.html?utm_medium=hp-10mar-menswear&amp;utm_source=hp"><img src="<?php echo $mediaUrl;?>wysiwyg/homepage/28-11-22/Final-Part-39_2.jpg"></a>
                </div>
                <div class="style-item style-items">
                    <a href="kids-wear.html?utm_medium=hp-10mar-kidswear&amp;utm_source=hp"><img src="<?php echo $mediaUrl;?>wysiwyg/homepage/28-11-22/Final-Part-40_2.jpg"></a>
                </div>
            </div>
        </div>

        <div class="content-heading">
            <h3 class="title earth"><img src="<?php echo $mediaUrl;?>wysiwyg/homepage/02-12-21/earth.jpg" alt=""></h3>
        </div>

        <div class="earth-friendly-curate">
            <div class="earth-curate">

                <div class="earth-item">
                    <a href="clothing.html?firstAttemptedFilter=acoeditFilter&amp;acoeditFilter=6209"><img src="<?php echo $mediaUrl;?>wysiwyg/homepage/28-11-22/Final-Part-41.jpg"></a>
                </div>

                <div class="earth-item friendly-items">
                    <a href="designers/mulmul.html"><img src="<?php echo $mediaUrl;?>wysiwyg/homepage/28-11-22/Final-Part-42.jpg"></a>
                </div>

                <div class="earth-item">
                    <a href="clothing.html?firstAttemptedFilter=acoeditFilter&amp;acoeditFilter=6223"><img src="<?php echo $mediaUrl;?>wysiwyg/homepage/28-11-22/Final-Part-43.jpg"></a>
                </div>
            </div>
        </div>

        <div class="best-seller-block">
            <div class="bestseller-patch"><img src="<?php echo $mediaUrl;?>wysiwyg/homepage/02-12-21/bs5.png"></div>
            <div class="bestseller-img-plot">
                <div class="bestseller-next">
                    <img src="<?php echo $mediaUrl;?>Homepage/Banner/img/right-arrow.svg">
                </div>                     
                <div class="bestseller-previous">
                    <img src="<?php echo $mediaUrl;?>Homepage/Banner/img/left-arrow.svg">
                </div>

                <div class="bestseller-slider">
                    <div class="best-sel-item">
                        <a href="torani-burgundy-printed-pre-draped-sari-hotgulsep2211.html"><img src="<?php echo $mediaUrl;?>wysiwyg/homepage/28-11-22/Final-Part-44.jpg"></a>
                    </div>
                    <div class="best-sel-item">
                        <a href="amyra-champagne-embroidered-bucket-bag-ayrsep2204.html"><img src="<?php echo $mediaUrl;?>wysiwyg/homepage/28-11-22/Final-Part-45.jpg"></a>
                    </div>
                    <div class="best-sel-item">
                        <a href="sabyasachi-sacabe001021mt-mustard-tan-bengal-tiger-belt.html"><img src="<?php echo $mediaUrl;?>wysiwyg/homepage/28-11-22/Final-Part-46.jpg"></a>
                    </div>
                    <div class="best-sel-item">
                        <a href="sheetal-batra-pink-embroidered-kurta-palazzo-set-stbnoor2205.html"><img src="<?php echo $mediaUrl;?>wysiwyg/homepage/28-11-22/Final-Part-47.jpg"></a>
                    </div>
                    <div class="best-sel-item">
                        <a href="suhani-pittie-suhs2206.html"><img src="<?php echo $mediaUrl;?>wysiwyg/homepage/28-11-22/Final-Part-48.jpg"></a>
                    </div>
                    <div class="best-sel-item">
                        <a href="masaba-msbjan21001-black-asymmetric-kaftan.html"><img src="<?php echo $mediaUrl;?>wysiwyg/homepage/28-11-22/Final-Part-49.jpg"></a>
                    </div>
                    <div class="best-sel-item">
                        <a href="tizora-pachi-kundan-matha-patti-tiztzrn6lt017.html"><img src="<?php echo $mediaUrl;?>wysiwyg/homepage/28-11-22/Final-Part-51.jpg"></a>
                    </div>
                    <div class="best-sel-item">
                        <a href="rajdeep-ranawat-carrot-printed-lehenga-set-rajmasju2201.html"><img src="<?php echo $mediaUrl;?>wysiwyg/homepage/28-11-22/Final-Part-52.jpg"></a>
                    </div>
                    <div class="best-sel-item">
                        <a href="house-of-vian-pastel-embroidered-juttis-via22vj139.html"><img src="<?php echo $mediaUrl;?>wysiwyg/homepage/28-11-22/Final-Part-53.jpg"></a>
                    </div>
                    <div class="best-sel-item">
                        <a href="vvani-by-vani-vats-mustard-embellished-sharara-set-vvajhalak2232.html"><img src="<?php echo $mediaUrl;?>wysiwyg/homepage/28-11-22/Final-Part-54.jpg"></a>
                    </div>
                    <div class="best-sel-item">
                        <a href="maisara-maimr67nc-kundan-jadau-and-pearl-choker-set.html"><img src="<?php echo $mediaUrl;?>wysiwyg/homepage/28-11-22/Final-Part-55.jpg"></a>
                    </div>
                    <div class="best-sel-item">
                        <a href="pomcha-jaipur-mustard-block-printed-kurta-set-pmjpjs1154.html"><img src="<?php echo $mediaUrl;?>wysiwyg/homepage/28-11-22/Final-Part-56.jpg"></a>
                    </div>
                </div>
            </div>
        </div>

        <div class="design-wear-block">
            <div class="kidswear-revolution">
                <div class="kids-wear"><a href="https://journal.aashniandco.com/2022/07/27/indian-kidswear-gets-a-makeover/"><img src="<?php echo $mediaUrl;?>wysiwyg/homepage/28-11-22/how_celebrity.jpg"></a></div>
            </div>
            <div class="categories-plot">
                <div class="category-pod">
                    <div class="cate-plot"><a href="https://journal.aashniandco.com/2022/08/24/whats-changed-for-the-brides-of-2022/"><img src="<?php echo $mediaUrl;?>wysiwyg/homepage/28-11-22/j1.jpg"></a></div>
                </div>
                <div class="category-pod">
                    <div class="cate-plot"><a href="https://journal.aashniandco.com/2022/06/28/the-changing-face-of-contemporary-menswear-in-india/"><img src="<?php echo $mediaUrl;?>wysiwyg/homepage/28-11-22/j2-new.jpeg"></a></div>
                </div>
                <div class="category-pod">
                    <div class="cate-plot"><a href="https://journal.aashniandco.com/2022/02/03/the-all-rounder-edit/"><img src="<?php echo $mediaUrl;?>wysiwyg/homepage/28-11-22/j3.jpg"></a></div>
                </div>
                <div class="category-pod">
                    <div class="cate-plot"><a href="https://journal.aashniandco.com/2021/12/15/how-to-create-a-mindful-bridal-trousseau/"><img src="<?php echo $mediaUrl;?>wysiwyg/homepage/28-11-22/j4.jpg"></a></div>
                </div>
            </div>
        </div>

        <div class="white-bg" id="newsletter-plot" style="display: none;">   
            <div class="block-popup-subscribe">
                <div class="newsletters">
                    <div class="close"><img src=<?php echo $mediaUrl."Homepage/Banner/img/cls-btn.svg"?>></div>
                    <div class="newsletter_plot">
                        <div class="news-letter-img"><img src="pub/media/wysiwyg/homepage/28-11-22/newsletters.avif"></div>
                        <div class="content-block">
                            <div class="content">
                                <form class="form subscribe">
                                    <div class="field">
                                        <div class="control">
                                            <input name="email" type="email" placeholder="Enter your email address" id="newsletter-email">
                                        </div>
                                    </div>
                                    <div class="actions">
                                        <button class="action subscribe btn btn-primary" title="Subscribe" type="button" id="newsletter-subscribe">
                                            <span>Subscribe</span>
                                        </button>
                                    </div>
                                    <div class="checkbox">
                                        <label for="dont_show">
                                            <input type="checkbox">
                                            Don't show this popup again
                                        </label>
                                    </div>
                                </form>
                            </div>                                  
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <script type="text/javascript" src="<?php echo $baseUrl;?>pub/static/frontend/Mgs/ethan/en_US/Fermion_Pagelayout/js/jquery-3.3.1.min.js"></script>
    <script type="text/javascript" src="<?php echo $baseUrl;?>pub/static/frontend/Mgs/ethan/en_US/Fermion_Pagelayout/js/slick.js"></script>
    <script type="text/javascript" src="<?php echo $baseUrl;?>pub/static/frontend/Mgs/ethan/en_US/Fermion_Pagelayout/js/home.js"></script> 

    <!-- <script src="skin/js/jquery-3.3.1.min.js"></script>
    <script src="skin/js/slick.js"></script>
    <script src="skin/js/home.js"></script>  -->

    <!-- <script type="text/javascript">
        $('.banner-slider').click({
            dots: true,
            infinite: true,
            speed: 600,
            slidesToShow: 1,
            slidesToScroll: 1,
            arrows: true,
            autoplay: true,
            draggable: false
        });


        $('.newin-slider').click({
            dots: false,
            infinite: false,
            slidesToShow: 5,
            slidesToScroll: 1,
            draggable: false,
            autoplay:true,
            arrows: true,
            prevArrow: $('.newin-previous'),
            nextArrow: $('.newin-next'),               
              responsive: [
               {
                  breakpoint: 1025,
                  settings: { 
                    autoplay:false,
                    infinite: true 
                  }
                },
                {
                  breakpoint: 768,
                  settings: {
                    autoplay:false,
                    slidesToShow: 2.5,
                    slidesToScroll: 1,
                    infinite: true,
                    centerMode: false,
                    centerPadding: '12%',
                  }
                },
                {
                  breakpoint: 480,
                  settings: {
                    slidesToShow: 1,
                    slidesToShow: 1,
                    centerPadding: '40px'
                  }
                }
              ]
        }); 

        $('.a-coedit-slider').click({
            dots: false,
            infinite: false,
            slidesToShow: 6,
            slidesToScroll: 1,
            draggable: false,
            autoplay:true,
            arrows: true,
            prevArrow: $('.co-edi-previous'),
            nextArrow: $('.co-edi-next'),               
              responsive: [
               {
                  breakpoint: 1025,
                  settings: { 
                    autoplay:false,
                    infinite: true 
                  }
                },
                {
                  breakpoint: 768,
                  settings: {
                    autoplay:false,
                    slidesToShow: 2.5,
                    slidesToScroll: 1,
                    infinite: true,
                    centerMode: false,
                    centerPadding: '12%',
                  }
                },
                {
                  breakpoint: 480,
                  settings: {
                    slidesToShow: 2.3,
                    slidesToShow: 1,
                    centerPadding: '40px'
                  }
                }
              ]
        });

        $('.access-slider').click({
            dots: false,
            infinite: false,
            slidesToShow: 4.9,
            slidesToScroll: 1,
            draggable: false,
            autoplay:true,
            arrows: false,
            prevArrow: $('.co-edi-previous'),
            nextArrow: $('.co-edi-next'),               
              responsive: [
               {
                  breakpoint: 1025,
                  settings: { 
                    autoplay:false,
                    infinite: true 
                  }
                },
                {
                  breakpoint: 768,
                  settings: {
                    autoplay:false,
                    slidesToShow: 2.5,
                    slidesToScroll: 1,
                    infinite: true,
                    centerMode: false,
                    centerPadding: '12%',
                  }
                },
                {
                  breakpoint: 480,
                  settings: {
                    slidesToShow: 2.3,
                    slidesToShow: 1,
                    centerPadding: '40px'
                  }
                }
              ]
        });

        $('.bestseller-slider').click({
            dots: false,
            infinite: false,
            slidesToShow: 6.1,
            slidesToScroll: 1,
            draggable: false,
            autoplay:true,
            arrows: true,
            prevArrow: $('.bestseller-previous'),
            nextArrow: $('.bestseller-next'),               
              responsive: [
               {
                  breakpoint: 1025,
                  settings: { 
                    autoplay:false,
                    infinite: true 
                  }
                },
                {
                  breakpoint: 768,
                  settings: {
                    autoplay:false,
                    slidesToShow: 2.5,
                    slidesToScroll: 1,
                    infinite: true,
                    centerMode: false,
                    centerPadding: '12%',
                  }
                },
                {
                  breakpoint: 480,
                  settings: {
                    slidesToShow: 2.3,
                    slidesToShow: 1,
                    centerPadding: '40px'
                  }
                }
              ]
        }); 
    </script> -->

<!-- </body>
</html> -->