<?php
/**
 * Copyright Â© 2015 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */
use Magento\Framework\App\Action\Action;

// @codingStandardsIgnoreFile

?>
<?php
/**
 * Product list template
 *
 * @var $block \Magento\Catalog\Block\Product\ListProduct
 */
?>
<?php
$_productCollection = $block->getLoadedProductCollection();

if(isset($_GET['mnhtest'])){
	//$_productCollection->getSelect()->reset(Zend_Db_Select::ORDER);
	echo $_productCollection->getSelect();die;

}

$_helper = $this->helper('Magento\Catalog\Helper\Output');
$themeHelper = $this->helper('MGS\Mpanel\Helper\Data');

$lazyLoad = $themeHelper->getStoreConfig('mgstheme/general/lazy_load');
$baseImage = $this->getViewFileUrl('MGS_Mpanel::images/blank.png');

$colClassRow = $themeHelper->getColClass();
$arrColClass = explode(' ', $colClassRow);
$pageType = 'catalog';
$settings = $themeHelper->getThemeSettings();
$perrow = $settings['catalog']['per_row'];
if($this->hasData('page_type')){
	$pageType = $this->getData('page_type');
}
$celebrityCat=false;
if($pageType == 'catalog'){
	$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
	$category = $objectManager->get('Magento\Framework\Registry')->registry('current_category');
	$categoryId = $category->getId();
	if($categoryId=='1383'):
		$celebrityCat=true;
	endif;

	if($category->getPerRow()){
		$perrow = $category->getPerRow();
	}
}elseif($pageType == 'catalogsearch') {
	if($settings['catalogsearch']['per_row']){
		$perrow = $settings['catalogsearch']['per_row'];
	}
}elseif($pageType == 'catalog_brand') {
	if($settings['catalog_brand']['per_row']){
		$perrow = $settings['catalog_brand']['per_row'];
	}
}

$colCheck = $themeHelper->convertPerRowtoCol($perrow);
$colClass = $themeHelper->convertColClass($colCheck, 'col');
?>
<?php if (!$_productCollection->count()): ?>
    <div class="message info empty"><div><?php /* @escapeNotVerified */ echo __('We can\'t find products matching the selection.') ?></div></div>
<?php else: ?>
	<div class="category-product-actions">
		<?php echo $block->getToolbarHtml() ?>
		<?php echo $block->getAdditionalHtml() ?>
	</div>
    <?php
    if ($block->getMode() == 'grid') {
        $viewMode = 'grid';
        $image = 'category_page_grid';
		$image_hover = 'product_base_image';
        $showDescription = false;
        $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::SHORT_VIEW;
    } else {
        $viewMode = 'list';
        $image = 'category_page_list';
		$image_hover = 'product_base_image';
        $showDescription = true;
        $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::FULL_VIEW;
    }
    /**
     * Position for actions regarding image size changing in vde if needed
     */
    $pos = $block->getPositioned();
    ?>

 <style>
@media only screen and (min-width: 600px) {
#listEnquiryModal .modal-dialog {
    width: 450px;
}
}
#listEnquiryModal .modal-title {
    font-family: 'Prata', serif;
    text-align: center;
}
#listEnquiryModal .modal-footer {
    display: none;
}
#listEnquiryModal .close {
    color: #000;
    border: 1px #000 solid;
    padding: 5px 10px;
    position: absolute;
    right: -16px;
    top: -18px;
    background: #000 !important;
    opacity: unset !important;
    border-radius: 21px;
    border: 2px #ccc solid;
}
#listEnquiryModal .close span {
    color: #fff;
}
#listEnquiryModal .button {
    background: #000;
    border: 1px #000 solid;
    color: #fff;
    padding: 8px 25px;
    margin-top: 15px;
}
</style>

    <div class="products wrapper <?php /* @escapeNotVerified */ echo $viewMode; ?> products-<?php /* @escapeNotVerified */ echo $viewMode; ?>" id="product-wrapper">
        <?php $iterator = 1; ?>
        <ol class="products list items product-items <?php if ($block->getMode() == 'grid'): ?>row<?php endif ?> <?php echo 'row-'.$arrColClass[0] ?>">
		
			<?php $_imagehelper = $this->helper('Magento\Catalog\Helper\Image'); ?>
			<?php $size = $themeHelper->getImageSize(); ?>
			<?php $quickViewHelper = $this->helper('MGS\QuickView\Helper\Data'); ?>
			<?php $compareHelper = $this->helper('Magento\Catalog\Helper\Product\Compare'); ?>
			
			<?php if ($block->getMode() == 'grid'): ?>
				<?php $params = $block->getRequest()->getParams();  ?>
				<?php if($settings['catalog']['ajaxscroll']): ?>
				
					<?php if(isset($params['product_list_limit'])): ?>
						<?php $countAll = $params['product_list_limit']; ?>
					<?php else: ?>
						<?php $countAll = $themeHelper->getStoreConfig('catalog/frontend/grid_per_page'); ?>		
					<?php endif ?>
					
					<?php if(isset($params['p'])): ?>
						<?php $i = ($params['p'] - 1) * $countAll; ?>
					<?php else: ?>
						<?php $i = 0; ?>
					<?php endif ?>
					
				<?php else: ?>
					<?php $i = 0; ?>
				<?php endif ?>
				
				<?php /** @var $_product \Magento\Catalog\Model\Product */ ?>
				<?php foreach ($_productCollection as $_product): $i++; ?>
					<li class="item product product-item-info product-item <?php echo $colClass ?> <?php echo $themeHelper->getClearClass($perrow, $i) ?>">
						<?php $_productNameStripped = $block->stripTags($_product->getName(), null, true); ?>
						<?php $productImage = $_imagehelper->init($_product, $image)->resize($size['width'], $size['height'])->getUrl(); ?>
                                        	<?php if( $celebrityCat  && $_product->getCelebrityImage()!='no_selection'):
                                        		$celebrityImage = $_imagehelper->init($_product, 'celebrity_image')->resize($size['width'], $size['height'])->getUrl();
                                       	 		$productImage = $celebrityImage;
                                        	endif;	
						?>				
						<?php if(!$lazyLoad){
							$baseImage = $productImage;
						} ?>
						<div class="product-top">
							<a href="<?php echo $_product->getProductUrl() ?>" class="product photo product-item-photo" tabindex="-1">
								<img src="<?php echo $baseImage; ?>" alt="<?php echo $_productNameStripped ?>" class="img-responsive product-image-photo img-thumbnail<?php if($lazyLoad): ?> lazy<?php endif ?>" data-original="<?php echo $productImage; ?>"/>
							</a>
							<?php echo $themeHelper->getProductLabel($_product) ?>
							<ul class="actions-link" data-role="add-to-links">
							
								<li class="hidden-sm hidden-xs"><?php if(!$_product->getHideprice()): echo $quickViewHelper->aroundQuickViewHtml($_product); endif; ?></li>
								<?php if(!$_product->getHideprice()):?>
								<?php if ($this->helper('Magento\Wishlist\Helper\Data')->isAllow() && !$settings['catalog']['wishlist_button']): ?>
									<li><button data-title="<?php echo $block->escapeHtml(__('Add to Wish List')); ?>"
									   class="action towishlist"
									   title="<?php echo $block->escapeHtml(__('Add to Wish List')); ?>"
									   aria-label="<?php echo $block->escapeHtml(__('Add to Wish List')); ?>"
									   data-post='<?php /* @escapeNotVerified */ echo $block->getAddToWishlistParams($_product); ?>'
									   data-action="add-to-wishlist"
									   role="button">
										<i class="fa fa-heart"></i>
									</button></li>
								<?php endif; ?>
									
								<?php if(!$settings['catalog']['compare_button']): ?>
									<li><button data-title="<?php echo $block->escapeHtml(__('Add to Compare')); ?>"
									   class="action tocompare"
									   title="<?php echo $block->escapeHtml(__('Add to Compare')); ?>"
									   aria-label="<?php echo $block->escapeHtml(__('Add to Compare')); ?>"
									   data-post='<?php /* @escapeNotVerified */ echo $compareHelper->getPostDataParams($_product); ?>'
									   role="button">
										<i class="fa fa-retweet"></i>
									</button></li>
								<?php endif ?>
								<?php endif?>
								<?php if ($_product->isSaleable() && !$_product->getHideprice()): ?>
									<li><?php $postParams = $block->getAddToCartPostParams($_product); ?>
									<?php $postParams = $block->getAddToCartPostParams($_product); ?>
									<form data-role="tocart-form" action="<?php /* @escapeNotVerified */ echo $this->getUrl('checkout/cart/add', ['uenc'=>$postParams['data'][Action::PARAM_NAME_URL_ENCODED], 'product'=>$postParams['data']['product']]); ?>" method="post">
										<input type="hidden" name="product" value="<?php /* @escapeNotVerified */ echo $postParams['data']['product']; ?>">
										<input type="hidden" name="<?php /* @escapeNotVerified */ echo Action::PARAM_NAME_URL_ENCODED; ?>" value="<?php /* @escapeNotVerified */ echo $postParams['data'][Action::PARAM_NAME_URL_ENCODED]; ?>">
										<?php echo $block->getBlockHtml('formkey')?>
										<button type="submit"
												title="<?php echo $block->escapeHtml(__('Add to Cart')); ?>"
												class="action tocart">
											<span class="fa fa-shopping-cart"></span>
										</button>
									</form></li>
								<?php endif ?>
							</ul>
						</div>
						<div class="product details product-item-details">
							<?php if( $celebrityCat ) :?>
                                                              <p class="celeb_name"><?php echo $_product->getCelebrityName(); ?></p>
                                                              <p class="celeb_in">in</p>
                                                        <?php endif; ?>
							<h5 class="product name product-item-name">
								<a class="product-item-link" href="<?php echo $_product->getProductUrl() ?>">
									<?php echo $_helper->productAttribute($_product, $_product->getName(), 'name'); ?>
								</a>
							</h5>
							<div class="product description product-item-description">
								<?php /* @escapeNotVerified */ echo $_helper->productAttribute($_product, $_product->getShortDescription(), 'short_description') ?>
								<a href="<?php /* @escapeNotVerified */ echo $_product->getProductUrl() ?>" title="<?php /* @escapeNotVerified */ echo $_productNameStripped ?>" class="action more">
								</a>
							</div>
							
							<?php echo $block->getProductDetailsHtml($_product); ?>
							
							<?php #echo $block->getProductPrice($_product) ?>
							<?php if(!$_product->getHideprice()){?>
							<?php echo $block->getProductPrice($_product) ?>
                                                        <?php $tag = $block->getTag($_product->getId()); ?>
						        <?php if(!empty($tag)){ ?>
						        <div class="product-tag"><span  style="background: #fff; z-index:28; color: #000; padding: 5px 25px; position: relative; top: 8px; border:1px #000 solid;">
							<?php echo $tag; ?>
						        </span></div>
							<?php } ?>
							<?php }else {?>
							<!--<span id="modal-btn" style="background: #fff; z-index:28; color: #000; padding: 5px 25px; position: relative; top: 8px; border:1px #000 solid;" data-toggle="modal" data-book-id="<?php //echo $_product->getSku();?>">Enquire Now</span>-->
                                                        <button type="button"
                                                                          style="background: #fff; z-index:28; color: #000; padding: 5px 25px;
                                                                          position: relative; top: 8px; border:1px #000 solid;"
                                                                          class="btn btn-primary" data-toggle="modal"
                                                                          data-target="#listEnquiryModal"
                                                                          data-sku="<?php echo $_product->getSku(); ?>"
                                                                          data-description="<?php echo $_product->getShortDescription(); ?>"
                                                                          data-name="<?php echo $_product->getName(); ?>">Enquire Now </button>

							<?php }?>

						</div>
						<?php if ($_product->isSaleable() == 0): ?>
							<div style="text-align:center" class="sold-out">Sold Out</div>
						<?php endif; ?>
					</li>
				<?php endforeach ?>
			<?php else: ?>
				<?php /** @var $_product \Magento\Catalog\Model\Product */ ?>
				<?php foreach ($_productCollection as $_product): ?>
					<?php $_productNameStripped = $block->stripTags($_product->getName(), null, true); ?>
					<?php $productImage = $_imagehelper->init($_product, $image)->resize($size['width'], $size['height'])->getUrl(); ?>
                                        <?php if( $celebrityCat  && $_product->getCelebrityImage()!='no_selection'):
                                        	$celebrityImage = $_imagehelper->init($_product, 'celebrity_image')->resize($size['width'], $size['height'])->getUrl();
                                        	$productImage = $celebrityImage;
                                        	endif;
					?>
					<?php if(!$lazyLoad){
						$baseImage = $productImage;
					} ?>
					<li class="item product product-item-info product-item">
						<div class="row">
							<div class="col-md-3 col-sm-4 col-xs-12">
								<div class="product-image-content">
									<a href="<?php echo $_product->getProductUrl() ?>" class="product photo product-item-photo" tabindex="-1">
										<img src="<?php echo $baseImage; ?>" alt="<?php echo $_productNameStripped ?>" class="img-responsive product-image-photo img-thumbnail<?php if($lazyLoad): ?> lazy<?php endif ?>" data-original="<?php echo $productImage; ?>"/>
									</a>
									<?php echo $themeHelper->getProductLabel($_product) ?>
								</div>
							</div>
							<div class="col-md-9 col-sm-8 col-xs-12">
								<div class="product details product-item-details">
									<?php if( $celebrityCat ) :?>
                	                                                        <p class="celeb_name"><?php echo $_product->getCelebrityName(); ?></p>
        	                                                                <p class="celeb_in">in</p>
	                                                                <?php endif; ?>
									<h5 class="product name product-item-name">
										<a class="product-item-link" href="<?php echo $_product->getProductUrl() ?>">
											<?php echo $_helper->productAttribute($_product, $_product->getName(), 'name'); ?>
										</a>
									</h5>
									
									<?php echo $block->getReviewsSummaryHtml($_product, $templateType,true); ?>
									
									<?php echo $block->getProductDetailsHtml($_product); ?>
									
									<?php #echo $block->getProductPrice($_product) ?>
									<?php #echo $block->getProductPrice($_product) ?>
									<?php if(!$_product->getHideprice()){?>
       									<?php echo $block->getProductPrice($_product) ?>
                                                                        <?php $tag = $block->getTag($_product->getId()); ?>
                                                                        <?php if(!empty($tag)){ ?>
                                                                        <div><span  style="background: #fff; z-index:28; color: #000; padding: 5px 25px; position: relative; top: 8px; $
                                                                        <?php echo $tag; ?>
                                                                        </span></div>
                                                                        <?php } ?>

									<?php }else {?>
									<!--<span id="modal-btn" style="background: #fff; z-index:28; color: #000; padding: 5px 25px; position: relative; top: 8px; border:1px #000 solid;" data-toggle="modal" data-book-id="<?php //echo $_product->getSku();?>">Enquire Now</span>-->
                                                                        <button type="button"
                                                                          style="background: #fff; z-index:28; color: #000; padding: 5px 25px;
                                                                          position: relative; top: 8px; border:1px #000 solid;"
                                                                          class="btn btn-primary" data-toggle="modal"
                                                                          data-target="#listEnquiryModal"
                                                                          data-sku="<?php echo $_product->getSku(); ?>"
                                                                          data-description="<?php echo $_product->getShortDescription(); ?>"
                                                                          data-name="<?php echo $_product->getName(); ?>">Enquire Now </button>
	
								<?php }?>

									
									<div class="product description product-item-description">
										<?php /* @escapeNotVerified */ echo $_helper->productAttribute($_product, $_product->getShortDescription(), 'short_description') ?>
										<a href="<?php /* @escapeNotVerified */ echo $_product->getProductUrl() ?>" title="<?php /* @escapeNotVerified */ echo $_productNameStripped ?>"
										   class="action more"></a>
									</div>
									
									<ul class="actions-link" data-role="add-to-links">
									
										<?php if ($_product->isSaleable() && !$_product->getHideprice() ): ?>
											<li><?php $postParams = $block->getAddToCartPostParams($_product); ?>
											<form data-role="tocart-form" action="<?php /* @escapeNotVerified */ echo $postParams['action']; ?>" method="post">
												<input type="hidden" name="product" value="<?php /* @escapeNotVerified */ echo $postParams['data']['product']; ?>">
												<input type="hidden" name="<?php /* @escapeNotVerified */ echo Action::PARAM_NAME_URL_ENCODED; ?>" value="<?php /* @escapeNotVerified */ echo $postParams['data'][Action::PARAM_NAME_URL_ENCODED]; ?>">
												<?php echo $block->getBlockHtml('formkey')?>
												<button type="submit"
														title="<?php echo $block->escapeHtml(__('Add to Cart')); ?>"
														class="action tocart">
													<span class="fa fa-shopping-cart"></span><span><?php echo $block->escapeHtml(__('Add To Cart')); ?></span>
												</button>
											</form></li>
										<?php endif ?>

										<?php if(!$_product->getHideprice()):?>	
										<?php if ($this->helper('Magento\Wishlist\Helper\Data')->isAllow() && !$settings['catalog']['wishlist_button']): ?>
											<li><button data-title="<?php echo $block->escapeHtml(__('Add to Wish List')); ?>"
											   class="action towishlist"
											   title="<?php echo $block->escapeHtml(__('Add to Wish List')); ?>"
											   aria-label="<?php echo $block->escapeHtml(__('Add to Wish List')); ?>"
											   data-post='<?php /* @escapeNotVerified */ echo $block->getAddToWishlistParams($_product); ?>'
											   data-action="add-to-wishlist"
											   role="button">
												<i class="fa fa-heart"></i>
											</button></li>
										<?php endif; ?>
											
										<?php if(!$settings['catalog']['compare_button']): ?>
											<li><button data-title="<?php echo $block->escapeHtml(__('Add to Compare')); ?>"
											   class="action tocompare"
											   title="<?php echo $block->escapeHtml(__('Add to Compare')); ?>"
											   aria-label="<?php echo $block->escapeHtml(__('Add to Compare')); ?>"
											   data-post='<?php /* @escapeNotVerified */ echo $compareHelper->getPostDataParams($_product); ?>'
											   role="button">
												<i class="fa fa-retweet"></i>
											</button></li>
										<?php endif ?>
										<?php endif ?>
										
										<li class="hidden-sm hidden-xs"><?php if(!$_product->getHideprice()): echo $quickViewHelper->aroundQuickViewHtml($_product); endif;?></li>
										
									</ul>
								</div>
							</div>
						</div>
					</li>
				<?php endforeach ?>
			<?php endif ?>
        </ol>
    </div>
	<div class="bottom-pagination<?php if($themeHelper->getStoreConfig('mpanel/catalog/ajaxscroll')): ?> ajaxscroll-enable<?php endif ?>">
		<?php echo $block->getToolbarHtml() ?>
	</div>
    <?php if (!$block->isRedirectToCartEnabled()) : ?>
        <script type="text/x-magento-init">
        {
            "[data-role=tocart-form], .form.map.checkout": {
                "catalogAddToCart": {}
            }
        }
        </script>
    <?php endif; ?>
        <!---Enqury on List Page--->
	<div class="modal fade" id="listEnquiryModal" tabindex="-1" role="dialog" aria-labelledby="listEnquiryModalLabel" aria-hidden="true">
		<div class="modal-dialog" role="document">
			<div class="modal-content">
				<div class="modal-header">
					<h5 class="modal-title" id="listEnquiryModalLabel">New message</h5>
					<button type="button" class="close" data-dismiss="modal" aria-label="Close">
						<span aria-hidden="true">&times;</span>
					</button>
				</div>
				<div class="modal-body">
                                    <form action="/enquire" method="post" enctype="multipart/form-data" autocomplete="off"
						  data-hasrequired="* Required Fields" data-mage-init='{"validation":{}}'>
						<input type="hidden" id="product_sku" name="sku" value="<?php //echo $_product->getSku() ?>">
						<input type="hidden" id="designer_name" name="designer_name" value="<?php //echo $_product->getName() ?>">
						<input type="hidden" id="product_desc" name="product_desc" value="<?php //echo $_product->getShortDescription() ?>">
						<input type="hidden" name="remote_ip" id="remote_ip" title="Client IP" class="input-text required-entry" value="<?php echo $_SERVER['REMOTE_ADDR'] ?>">
						<ul class="form-list">
							<li>
								<div class="field">
									<label for="name" class="required">Name</label>
									<div class="input-box">
										<input name="customer_name" id="customer_name" title="Name" value="" class="input-text required-entry" type="text" data-validate="{required:true}" />
									</div>
								</div>
							</li>
							<li>
								<div class="field">
									<label for="email" class="required">Email</label>
									<div class="input-box">
										<input name="customer_email" id="customer_email" title="Email" value="" class="input-text required-entry validate-email" type="text">
									</div>
								</div>
							</li>
							<li>
								<div class="field">
									<label for="phone" class="required">Phone</label>
									<div class="input-box">
										<input name="customer_phone" id="customer_phone" title="Phone" value="" class="input-text validate-number" type="text">
									</div>
								</div>
							</li>
							<li>
								<div class="field">
									<label for="phone" class="required">Your Query</label>
									<div class="input-box">
										<input  name="query" id="query" title="Comments" value="" class="input-text required-entry" type="text">
									</div>
								</div>
							</li>
						</ul>

						<button  type="submit" title="Submit" class="button"><span><span>Submit</span></span></button>
					</form>
				</div>
				<!--<div class="modal-footer">
					<button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
					<button type="button" class="btn btn-primary">Send message</button>
				</div>-->
			</div>
		</div>
	</div>
	<!---Enquiry on List Page--->
        <script>
                require(['jquery'],function($) {
                $(document).ready(function () {

                console.log('Hello');
		$('#listEnquiryModal').on('show.bs.modal', function (event) {
			var button = $(event.relatedTarget); // Button that triggered the modal
			var product_name = button.data('name'); // Extract info from data* attributes
                        var product_sku = button.data('sku');
			var product_description = button.data('description');
			// If necessary, you could initiate an AJAX request here (and then do the updating in a callback).
			// Update the modal's content. We'll use jQuery here, but you could use a data binding library or other methods instead.
			var modal = $(this);
                        console.log('product_name'+product_name);
			modal.find('.modal-title').text(product_name);
			modal.find('.modal-body #designer_name').val(product_name);
                        modal.find('.modal-body #product_sku').val(product_sku);
			modal.find('.modal-body #product_desc').val(product_description);
		});
                });
                });
	</script>
<?php endif; ?>
