<?php 
$currentProduct = $block->getProduct();
$productUrl = $currentProduct->getProductUrl();
$productBaseImage = $block->getImage($currentProduct, 'product_base_image')->getImageUrl();
$productDescription = $currentProduct->getDescription();
?>

<div class="share-buttons">
	<span>SHARE </span>
    <a href="https://www.facebook.com/sharer/sharer.php?u=<?= $productUrl; ?>" target="_blank" rel="noopener noreferrer">
        <img src="/pub/media/logo/icons8-facebook.svg" alt="Share on Facebook">
    </a>
    <a href="https://www.instagram.com/direct/new/?text=<?= $productUrl; ?>" target="_blank" rel="noopener noreferrer">
        <img src="/pub/media/logo/icons8-instagram.svg" alt="Share on Instagram">
    </a>
    <a href="https://x.com/intent/tweet?url=<?= $productUrl; ?>" target="_blank" rel="noopener noreferrer">
        <img src="/pub/media/logo/icons8-twitterx.svg" alt="Share on X">
    </a>
    <a href="mailto:?subject=Check%20out%20this%20product!&body=<?= $productUrl; ?>" target="_blank" rel="noopener noreferrer">
        <img src="/pub/media/logo/icons8-gmail.svg" alt="Share via Email">
    </a>
    <a href="https://pinterest.com/pin/create/button/?url=<?= $productUrl ?>&media=<?= $productBaseImage; ?>&description=<?= $productDescription; ?>" target="_blank" rel="noopener noreferrer">
        <img src="/pub/media/logo/icons8-pinterest.svg" alt="Share on Pinterest">
    </a>
</div>

<style>
	.share-buttons img{
		width: 20px;
		margin-right: 10px;
	}
	.share-buttons span {
		margin-right: 10px;
	}
</style>