<?php
$baseUrl = $this->getBaseUrl(); 
$jsVersion = $this->getJsVersion(); 
//echo($jsVersion);die();
?>        
<div class="footer-container-wrapper">
         <div class="top-footer">
            <div class="top-footer-wrap">
               <div class="top-footer-container">
                  <p class="stay-in-touch"> STAY IN TOUCH  </p>
                  <div class="news-letter-wrap">
                     <form class=" subscribe-form" >
                        <div class="newsletter">
                           <div class="newsletter-input">
                              <input name="email" type="email" placeholder="Type your email here">
                              <div for="newsletter-footer" generated="true" class="mage-error" id="newsletter-footer-error" style="display: none;"></div>
                           </div>
                        </div>
                        <div class="actions-subscribe">
                           <button class="subscribe-btn"  type="button">
                           <span>Subscribe</span>
                           </button>
                        </div>
                     </form>
                     <div class="messages">
                        <div class="message message-error error">
                           <div></div>
                        </div>
                     </div>
                  </div>
               </div>
            </div>
         </div>
         <div class="middle-footer">
                        <div class="middle-footer-wrap">
               <div class="middle-footer-content">
                  <div class="main-heading">Shop Your Favorite Designer Clothing Online at Aashni &amp; Co</div>
                  <p class="footer-paragraph">Step into the world of South Asian luxury fashion with Aashni &amp; Co with curated pieces for brides and grooms. Set over three floors with haute couture, ready-to-wear collections, jewelry and accessories, the sought-after store brings a curated collection of South Asian luxury fashion for the brides and grooms.</p>
                  <p class="footer-paragraph">Aashni and Co’s website has a collection of 400+ luxury designers, which is your one-stop destination for your fashion needs, from Indian designer clothes to accessories online. Get your hands on luxury products at our online or our flagship store. Aashni &amp;  Co’s includes designs by ace couturiers' such as Sabyasachi, Anamika Khanna, Anita Dongre, Manish Malhotra, Vvani by Vani Vats, Seema Gujral, Gaurav Gupta, Masaba, Neeta Lulla, Tarun Tahiliani, Ridhi Mehra, Rohit Bal, Shivan &amp;  Narresh, and more.</p>
                  <p class="footer-paragraph">Aashni and Co offer a wide range of designer outfits, accessories, home decor and more. The designer range includes 
                     <a class="utm_class" href="<?=$baseUrl?>designer">
                        <span class="bold_text">Indian designer wear</span>
                      </a>, 
                      <a class="utm_class" href="<?=$baseUrl?>men.html">
                        <span class="bold_text">designer clothing for men</span>
                      </a>, 
                      <a class="utm_class" href="<?=$baseUrl?>clothing.html">
                        <span class="bold_text">designer clothes for women</span>
                      </a>, 
                      <a class="utm_class" href="<?=$baseUrl?>accessories/jewelry.html">
                        <span class="bold_text">designer jewelry</span>
                      </a>, 
                      <a class="utm_class" href="<?=$baseUrl?>homeware.html">
                        <span class="bold_text">Homeware</span>
                      </a>, and 
                      <a class="utm_class" href="<?=$baseUrl?>bridal">
                        <span class="bold_text">bridal trousseau essentials</span>
                      </a>.The clothing collection is available in all categories ranging from 
                      <a class="utm_class" href="<?=$baseUrl?>women-s-clothing/saris.html">
                        <span class="bold_text">designer sarees</span>
                      </a>, 
                      <a class="utm_class" href="<?=$baseUrl?>women-s-clothing/tunics-kurtis.html">
                        <span class="bold_text">kurtas</span>
                      </a>, 
                      <a class="utm_class" href="<?=$baseUrl?>women-s-clothing/lehengas.html">
                        <span class="bold_text">lehengas</span>
                      </a>, 
                      <a class="utm_class" href="<?=$baseUrl?>men/shirts.html">
                        <span class="bold_text">shirts</span>
                      </a>, 
                      <a class="utm_class" href="<?=$baseUrl?>men/jackets-and-blazers.html">
                        <span class="bold_text">jackets</span>
                      </a>, 
                      <a class="utm_class" href="<?=$baseUrl?>men/sherwani.html">
                        <span class="bold_text">sherwanis</span>
                      </a>, 
                      <a class="utm_class" href="<?=$baseUrl?>men/bandhgalas.html">
                        <span class="bold_text">bandhgalas</span>
                      </a>, 
                      <a class="utm_class" href="<?=$baseUrl?>kids-wear/kurta-sets-for-boys.html">
                        <span class="bold_text">kurtas for boys</span>
                      </a>, 
                      <a class="utm_class" href="<?=$baseUrl?>kids-wear/lehengas.html">
                        <span class="bold_text">lehengas for girls</span>
                      </a> and more.
                  </p>
                  <p class="footer-paragraph">Shop Indian designer ensembles and accessories for every occasion at Aashni &amp; Co. From designer ethnic clothing to indo-western &amp; contemporary wear, we have got you covered with everything to suit your personal style and preferences whether you are looking for casual, formal, semi-formal or occasion wear. You can find perfect Indian designer clothing for every event, whether it is a 
                     <a class="utm_class" href="<?=$baseUrl?>occasion/wedding.html">  <span class="bold_text">wedding</span></a> , 
                     <a class="utm_class" href="<?=$baseUrl?>occasion/engagement.html">  <span class="bold_text">engagement</span></a> , 
                     <a class="utm_class" href="<?=$baseUrl?>occasion/sangeet.html">  <span class="bold_text">sangeet</span></a> , 
                     <a class="utm_class" href="<?=$baseUrl?>occasion/reception.html">  <span class="bold_text">reception outfits for women</span></a> , 
                     <a class="utm_class" href="<?=$baseUrl?>occasion/haldi.html">  <span class="bold_text">Haldi &amp; </span></a>   
                     <a class="utm_class" href="<?=$baseUrl?>occasion/mehndi.html">  <span class="bold_text">Mehendi</span></a>
                     ceremony, poolside party, destination wedding, resort wedding, beach wedding,
                     <a class="utm_class" href="<?=$baseUrl?>occasion/puja.html">  <span class="bold_text">traditional pooja rituals</span></a> ,
                     <a class="utm_class" href="<?=$baseUrl?>occasion/cocktail.html">  <span class="bold_text">cocktail party </span></a>, 
                     brunch get-togethers, and other <a class="utm_class" href="<?=$baseUrl?>occasion/festive.html"> <span class="bold_text">festive</span></a> 
                     occasions. With so many exquisite and elegant styles available at A+C, make sure you dress for every appearance like a glorious diva.
                  </p>
                  <p class="footer-paragraph">For occasions like Diwali party, family get-togethers for 
                     <a class="utm_class" href="<?=$baseUrl?>occasion/eid.html">  <span class="bold_text">Eid   </span></a> 
                     , groovy 
                     <a class="utm_class" href="<?=$baseUrl?>occasion/navratri.html">  <span class="bold_text">Navratri nights   </span></a> , 
                     and celebrations like Ganesh Chaturthi, Gudi Padwa, Onam, Durga Pooja, Parsi New Year, Christmas, and more, at A+C you’ll get great outfits for every festivity. Browse through the ethnic designer collection curated for men, women &amp; kids. Shop traditional designer dresses, sarees, lehengas, kurtas for women &amp; girls, kurtas for men &amp; boys, sherwanis for men &amp; boys, and more.
                  </p>
                  <div class="txt-heading">Shop Exclusive Designer Clothing &amp; Accessories Collection at Aashni &amp; Co</div>
                  <p class="footer-paragraph">Select the finest luxury designers' wear on India's top fashion place- Aashni &amp;  Co. Shop for elite 
                     Indian designers' collections such as 
                     <a class="utm_class" href="<?=$baseUrl?>designers/sabyasachi.html"><span class="bold_text">Sabyasachi Mukherjee</span></a> , 
                     <a class="utm_class" href="<?=$baseUrl?>designers/manish-malhotra.html"><span class="bold_text">Manish Malhotra</span></a> , 
                     <a class="utm_class" href="<?=$baseUrl?>designers/anita-dongre.html"><span class="bold_text">Anita Dongre</span></a> , 
                     <a class="utm_class" href="<?=$baseUrl?>designers/fayon-kids-by-preeti-jatia.html"><span class="bold_text">Fayon Kids by Preeti Jatia</span></a> ,
                     <a class="utm_class" href="<?=$baseUrl?>designers/masaba.html"><span class="bold_text">Masaba</span></a> , 
                     <a class="utm_class" href="<?=$baseUrl?>designers/shivan-narresh.html"><span class="bold_text">Shivan & Narresh</span></a> , 
                     <a class="utm_class" href="<?=$baseUrl?>designers/tarun-tahiliani.html"><span class="bold_text">Tarun Tahiliani</span></a> , 
                     <a class="utm_class" href="<?=$baseUrl?>designers/joules-by-radhika.html"><span class="bold_text">Joules by Radhika </span></a>, 
                     and more. We offer everything from wedding wear to festive styles, from bridal trousseau to ethnic wear to designer grooms wear, under one roof. From designer jewellery to accessories with the finest designs and meticulously curated collections are available at Aashni & Co online store as well as at London flagship store! Shop for the latest Indian ethnic designer wear and western clothing by your favourite premium designers.
                  </p>
                  <div class="txt-heading">Shop Premium Women Clothing Collection at Aashni &amp;  Co</div>
                  <p class="footer-paragraph">
                     At Aashni &amp; Co, you can never go wrong in selecting exquisite outfits, whether you are a bride-to-be, a bridesmaid, a working woman in the corporate world, a mother, a college graduate looking for a job, or simply a stylish diva with a passion for fashion. Our online store offers a wide variety of outfits, from one-of-a-kind runway couture to exclusive 
                     <a class="utm_class" href="<?=$baseUrl?>clothing.html">  <span class="bold_text">designer clothing for women   </span></a>
                     that can easily be part of your wardrobe.
                  </p>
                  <div class="txt-heading">Let's Explore Celebrity Closet at Aashni &amp; Co</div>
                  <p class="footer-paragraph">Bollywood fashion is now at your fingertips! Pinning fashion inspirations of your favourite  celebrity?   You can also own them now! Shop ultra-stylish celebrity-spotted looks from our 
                     <a class="utm_class" href="<?=$baseUrl?>celebrity-spotting.html">  <span class="bold_text">Celebrity Closet   </span></a>
                     under one stage at Aashni & Co exclusively. Get the look of your favorite Bollywood diva, whether it is <a class="utm_class" href="<?=$baseUrl?>celebrity-spotting/karishma-kapoor.html">  <span class="bold_text">Karishma Kapoor   </span></a>or 
                     <a class="utm_class" href="<?=$baseUrl?>celebrity-spotting/jhanvi-kapoor.html">  <span class="bold_text">Janhvi Kapoor   </span></a> , 
                     <a class="utm_class" href="<?=$baseUrl?>celebrity-spotting/kriti-sanon.html">  <span class="bold_text">Kriti Sanon   </span></a>or 
                     <a class="utm_class" href="<?=$baseUrl?>celebrity-spotting/alia-bhatt.html">  <span class="bold_text">Alia Bhatt   </span></a> , 
                     <a class="utm_class" href="<?=$baseUrl?>celebrity-spotting/kiara-advani.html">  <span class="bold_text">Kiara Advani   </span></a>or 
                     <a class="utm_class" href="<?=$baseUrl?>celebrity-spotting/vidya-balan.html">  <span class="bold_text">Vidya Balan   </span></a> , 
                     <a class="utm_class" href="<?=$baseUrl?>anita-dongre-andf21p62-red-ajrakh-lehenga-set.html">  <span class="bold_text">Tara Sutaria   </span></a> , 
                     <a class="utm_class" href="<?=$baseUrl?>maayera-jaipur-floral-printed-kurta-mrjdtsoct15.html">  <span class="bold_text">Salman Khan   </span></a> or <a class="utm_class" href="<?=$baseUrl?>celebrity-spotting/rajkummar-rao.html">  <span class="bold_text">Rajkumar Rao   </span></a>
                     straight to your closet now. Whether it's a red-carpet look, celebrity wedding attire, an outfit from a movie sequence, a movie premiere, or a promotional appearance, all your loved looks are ready to be part of your wardrobe, winning you the title of fashionista. Check out 
                     <a class="utm_class" href="<?=$baseUrl?>bridal/women-s-clothing/saris.html">  <span class="bold_text">designer sarees for weddings   </span></a> ,
                     <a class="utm_class" href="<?=$baseUrl?>women-s-clothing/saris/pre-draped-saris.html">  <span class="bold_text">pre draped saree   </span></a> , 
                     <a class="utm_class" href="<?=$baseUrl?>women-s-clothing/saris/handwoven-saris.html">  <span class="bold_text">handwoven sarees   </span></a> , 
                     <a class="utm_class" href="<?=$baseUrl?>women-s-clothing/jumpsuits.html">  <span class="bold_text">jumpsuits   </span></a> , 
                     <a class="utm_class" href="<?=$baseUrl?>women-s-clothing/lehengas/classic-lehengas.html">  <span class="bold_text">classic lehengas   </span></a> ,
                     <a class="utm_class" href="<?=$baseUrl?>women-s-clothing/saris/pants-and-dhoti-saris.html">  <span class="bold_text">pant style saree   </span></a> , 
                     <a class="utm_class" href="<?=$baseUrl?>women-s-clothing/saris/ruffle-saris.html">  <span class="bold_text">ruffle saree   </span></a>, and more online.
                  </p>
                  <div class="txt-heading">Keep Up with What Your Favorite Fashion Designer Icons Are up to</div>
                  <p class="footer-paragraph">The idea of creating an outfit from scratch and showcasing it to a large community of fans via the hashtag has aided individuals in understanding trends and making them suitable for daily wear. Imagine having every item of apparel and jewelry your favorite fashion icons wear. From Alia Bhatt to Madhuri Dixit Nene, Aashni &amp; Co Journal has a 
                     <a class="utm_class" href="https://journal.aashniandco.com/category/fashion-news/">  <span class="bold_text">'Fashion &amp; News'   </span></a>
                     feature to help track celebrity fashion trends and details of the outfits that are worth exploring. This way, you will never miss out on the 
                     <a class="utm_class" href="http://journal.aashniandco.com/">  <span class="bold_text">latest designer fashion trends   </span></a> from around the world.
                  </p>
                  <div class="txt-heading">New Product Launches and Trending Topics Updates</div>
                  <p class="footer-paragraph">Since fashion seems extremely hard to keep up with these days, a quick update on what is trending in accessories, clothing, and footwear would undoubtedly be of great help.</p>
                  <p class="footer-paragraph">Aashni &amp; Co's Journal helps you stay connected to the most beloved and sought-after fashion designers, such as 
                     <a class="utm_class" href="<?=$baseUrl?>designers/sabyasachi.html/"><span class="bold_text">Sabyasachi Mukherjee</span></a> , 
                     <a class="utm_class" href="<?=$baseUrl?>designers/anamika-khanna.html"><span class="bold_text">Anamika Khanna</span></a> , 
                     <a class="utm_class" href="<?=$baseUrl?>designers/manish-malhotra.html"><span class="bold_text">Manish Malhotra</span></a> , 
                     <a class="utm_class" href="<?=$baseUrl?>designers/tarun-tahiliani.html"><span class="bold_text">Tarun Tahiliani</span></a> , 
                     <a class="utm_class" href="<?=$baseUrl?>designers/suhani-pittie.html"><span class="bold_text">Suhani Pittie </span></a>,
                     and more. Stay tuned for the latest fashion updates on our social media platforms with stories of designer curations, exclusive drops and new arrivals.
                  </p>
                  <p class="footer-paragraph">
                     <a class="utm_class" href="https://www.instagram.com/aashniandco/" style="text-decoration: none;"><span class="bold_text">Instagram</span></a> |
                     <a class="utm_class" href="https://www.facebook.com/pages/Aashni-Co-Official/417895134941609" style="text-decoration: none;"><span class="bold_text">Facebook</span></a> |
                     <a class="utm_class" href="https://twitter.com/aashniuk" style="text-decoration: none;"><span class="bold_text">Twitter</span></a>
                  </p>
                  <div class="txt-heading">Explore Aashni + Co’s Luxury Clothing</div>
                  <div class="txt-heading">Top Designers for Clothing</div>
                  <p class="footer-paragraph">
                     <a class="utm_class" href="<?=$baseUrl?>designers/sabyasachi.html">  <span>Sabyasachi Mukherjee   </span></a>|
                     <a class="utm_class" href="<?=$baseUrl?>designers/tarun-tahiliani.html">  <span> Tarun Tahiliani   </span></a>|
                     <a class="utm_class" href="<?=$baseUrl?>designers/gulabo-by-abu-sandeep.html">  <span> Gulabo by Abu Sandeep   </span></a>|
                     <a class="utm_class" href="<?=$baseUrl?>designers/anamika-khanna.html">  <span> Anamika Khanna   </span></a>|
                     <a class="utm_class" href="<?=$baseUrl?>designers/angad-singh.html">  <span> Angad Singh   </span></a>|
                     <a class="utm_class" href="<?=$baseUrl?>designers/mahima-mahajan.html">  <span> Mahima Mahajan   </span></a>|
                     <a class="utm_class" href="<?=$baseUrl?>designers/amit-aggarwal.html">  <span> Amit Aggarwal   </span></a>|
                     <a class="utm_class" href="<?=$baseUrl?>designers/anushree-reddy.html">  <span> Anushree Reddy   </span></a>|
                     <a class="utm_class" href="<?=$baseUrl?>designers/seema-gujral.html">  <span> Seema Gujral   </span></a>|
                     <a class="utm_class" href="<?=$baseUrl?>designers/rohit-bal.html">  <span> Rohit Bal   </span></a>|
                     <a class="utm_class" href="<?=$baseUrl?>designers/varun-bahl.html">  <span> Varun Bahl   </span></a>|
                     <a class="utm_class" href="<?=$baseUrl?>designers/house-of-torani.html">  <span> Torani   </span></a>|
                     <a class="utm_class" href="<?=$baseUrl?>designers/ritu-kumar.html">  <span> Ritu Kumar   </span></a>|
                     <a class="utm_class" href="<?=$baseUrl?>designers/jayanti-reddy.html">  <span> Jayanti Reddy   </span></a>|
                     <a class="utm_class" href="<?=$baseUrl?>designers/ridhi-mehra.html">  <span> Ridhi Mehra   </span></a>|
                     <a class="utm_class" href="<?=$baseUrl?>designers/rohit-gandhi-rahul-khanna.html">  <span> Rohit Gandhi + Rahul Khanna   </span></a>|
                     <a class="utm_class" href="<?=$baseUrl?>designers/aisha-rao.html">  <span> Aisha Rao   </span></a>|
                     <a class="utm_class" href="<?=$baseUrl?>designers/abhinav-mishra.html">  <span> Abhinav Mishra   </span></a>|
                     <a class="utm_class" href="<?=$baseUrl?>designers/punit-balana.html">  <span> Punit Balana   </span></a>|
                     <a class="utm_class" href="<?=$baseUrl?>designers/jade-by-monica-and-karishma.html">  <span> Jade By Monica and Karishma   </span></a>|
                     <a class="utm_class" href="<?=$baseUrl?>designers/masaba.html">  <span> Masaba   </span></a>|
                     <a class="utm_class" href="<?=$baseUrl?>designers/ak-ok.html">  <span> AK-OK   </span></a>|
                     <a class="utm_class" href="<?=$baseUrl?>designers/payal-singhal.html">  <span> Payal Singhal   </span></a>|
                     <a class="utm_class" href="<?=$baseUrl?>designers/mishru.html">  <span> Mishru   </span></a>|
                     <a class="utm_class" href="<?=$baseUrl?>designers/ridhima-bhasin.html">  <span> Ridhima Bhasin   </span></a>|
                     <a class="utm_class" href="<?=$baseUrl?>designers/vvani-by-vani-vats.html">  <span> Vvani by Vani Vats   </span></a>|
                     <a class="utm_class" href="<?=$baseUrl?>designers/ritika-mirchandani.html">  <span> Ritika Mirchandani   </span></a>|
                     <a class="utm_class" href="<?=$baseUrl?>designers/sva-sonam-and-paras-modi.html">  <span> SVA By Sonam and Paras Modi   </span></a>|
                     <a class="utm_class" href="<?=$baseUrl?>designers/mrunalini-rao.html">  <span> Mrunalini Rao   </span></a>|
                     <a class="utm_class" href="<?=$baseUrl?>designers/shivan-narresh.html">  <span> Shivan &amp; Narresh   </span></a>|
                     <a class="utm_class" href="<?=$baseUrl?>designers/not-so-serious-by-pallavi-mohan.html">  <span> Not So Serious by Pallavi Mohan   </span></a>|
                     <a class="utm_class" href="<?=$baseUrl?>designers/rajdeep-ranawat.html">  <span> Rajdeep Ranawat   </span></a>|
                     <a class="utm_class" href="<?=$baseUrl?>designers/aneesh-agarwaal.html">  <span> Aneesh Agarwaal   </span></a>|
                     <a class="utm_class" href="<?=$baseUrl?>designers/bhumika-sharma.html">  <span> Bhumika Sharma   </span></a>|
                     <a class="utm_class" href="<?=$baseUrl?>designers/sukriti-akriti.html">  <span> Sukriti &amp; Aakriti   </span></a>|
                     <a class="utm_class" href="<?=$baseUrl?>designers/saaksha-kinni.html">  <span> Saaksha &amp; Kinni   </span></a>|
                     <a class="utm_class" href="<?=$baseUrl?>designers/431-88-by-shweta-kapur.html">  <span> 431-88 by Shweta Kapur   </span></a>|
                     <a class="utm_class" href="<?=$baseUrl?>designers/archana-jaju.html">  <span> Archana Jaju   </span></a>|
                     <a class="utm_class" href="<?=$baseUrl?>designers/astha-narang.html">  <span> Astha Narang   </span></a>|
                     <a class="utm_class" href="<?=$baseUrl?>designers/siddartha-tytler.html">  <span> Siddartha Tytler   </span></a>|
                     <a class="utm_class" href="<?=$baseUrl?>designers/gopi-vaid.html">  <span> Gopi Vaid   </span></a>|
                     <a class="utm_class" href="<?=$baseUrl?>designers/shyam-narayan-prasad.html">  <span> Shyam Narayan Prasad   </span></a>|
                     <a class="utm_class" href="<?=$baseUrl?>designers/just-shradha-s.html">  <span> Just Shradha's   </span></a>|
                     <a class="utm_class" href="<?=$baseUrl?>designers/just-jewellery.html">  <span> Just Jewelry   </span></a>|
                     <a class="utm_class" href="<?=$baseUrl?>designers/moh-maya-by-disha-khatri.html">  <span> Moh-Maya by Disha Khatri   </span></a>|
                     <a class="utm_class" href="<?=$baseUrl?>designers/ritika-sachdeva.html">  <span> Ritika Sachdeva   </span></a>
                  </p>
                  <div class="txt-heading">Top Categories in Women’s Clothing</div>
                  <p class="footer-paragraph">
                     <a class="utm_class" href="<?=$baseUrl?>womens-clothing.html"><span> All Clothing </span></a>|
                     <a class="utm_class" href="<?=$baseUrl?>womens-clothing/lehengas.html"><span> Lehengas </span></a>|
                     <a class="utm_class" href="<?=$baseUrl?>womens-clothing/dresses.html"><span> Dresses </span></a>|
                     <a class="utm_class" href="<?=$baseUrl?>womens-clothing/saris.html"><span> Saris </span></a>|
                     <a class="utm_class" href="<?=$baseUrl?>womens-clothing/jumpsuits.html"><span> Jumpsuits </span></a>|
                     <a class="utm_class" href="<?=$baseUrl?>womens-clothing/kurta-sets.html"><span> Kurta Sets </span></a>|
                     <a class="utm_class" href="<?=$baseUrl?>womens-clothing/tunics-kurtis.html"><span> Tunics &amp; Kurtis </span></a>|
                     <a class="utm_class" href="<?=$baseUrl?>womens-clothing/anarkalis.html"><span> Anarkalis </span></a>|
                     <a class="utm_class" href="<?=$baseUrl?>womens-clothing/gowns.html"><span> Gowns </span></a>|
                     <a class="utm_class" href="<?=$baseUrl?>clothing/kaftans.html"><span> Kaftans </span></a>|
                     <a class="utm_class" href="<?=$baseUrl?>womens-clothing/tops.html"><span> Tops </span></a>|
                     <a class="utm_class" href="<?=$baseUrl?>womens-clothing/pants.html"><span> Pants </span></a>|
                     <a class="utm_class" href="<?=$baseUrl?>womens-clothing/skirts.html"><span> Skirts </span></a>|
                     <a class="utm_class" href="<?=$baseUrl?>womens-clothing/co-ords.html"><span> Co-ords </span></a>|
                     <a class="utm_class" href="<?=$baseUrl?>womens-clothing/jackets.html"><span> Jackets </span></a>|
                     <a class="utm_class" href="<?=$baseUrl?>womens-clothing/capes.html"><span> Capes </span></a>|
                     <a class="utm_class" href="<?=$baseUrl?>womens-clothing/beach.html"><span> Beachwear </span></a>|
                     <a class="utm_class" href="<?=$baseUrl?>clothing/loungewear.html"><span> Loungewear </span></a>|
                     <a class="utm_class" href="<?=$baseUrl?>womens-clothing/sharara-sets.html"><span> Sharara Sets </span></a>|
                     <a class="utm_class" href="<?=$baseUrl?>womens-clothing.html?themeFilter=6045"><span> Ethnic </span></a>|
                     <a class="utm_class" href="<?=$baseUrl?>womens-clothing.html?themeFilter=6044"><span> Contemporary </span></a>
                  </p>
                  <div class="txt-heading">Top Categories in Men’s Clothing</div>
                  <p class="footer-paragraph"> 
                     <a class="utm_class" href="<?=$baseUrl?>men.html"><span> All Clothing </span></a>|
                     <a class="utm_class" href="<?=$baseUrl?>men/jackets.html"><span> Jackets </span></a>|
                     <a class="utm_class" href="<?=$baseUrl?>men/shirts.html"><span> Shirts </span></a>|
                     <a class="utm_class" href="<?=$baseUrl?>men/sherwani.html"><span> Sherwani </span></a>|
                     <a class="utm_class" href="<?=$baseUrl?>men/bandi-sets.html"><span> Bandi Sets </span></a>|
                     <a class="utm_class" href="<?=$baseUrl?>men/bandi.html%20?utm_source=google&amp;utm_medium=cpc&amp;utm_campaign=static%201&amp;utm_content=19feb"><span> Bandi </span></a>|
                     <a class="utm_class" href="<?=$baseUrl?>men/nehru-jackets.html.html"><span> Nehru Jackets </span></a>|
                     <a class="utm_class" href="<?=$baseUrl?>men/bandhgalas.html"><span> Bandhgalas </span></a>|
                     <a class="utm_class" href="<?=$baseUrl?>men/kurta-set.html"><span> Kurta Sets </span></a>|
                     <a class="utm_class" href="<?=$baseUrl?>men.html?firstAttemptedFilter=themeFilter&amp;themeFilter=6044"><span> Contemporary </span></a>|
                     <a class="utm_class" href="<?=$baseUrl?>men.html"><span> Ethnic </span></a>
                  </p>
                  <div class="txt-heading">Top Categories in Kids Clothing</div>
                  <p class="footer-paragraph"> 
                     <a class="utm_class" href="<?=$baseUrl?>kids-wear.html?utm_source=google&amp;utm_medium=cpc&amp;utm_campaign=static%201&amp;utm_content=19feb"><span> All Clothing </span></a>|
                     <a class="utm_class" href="<?=$baseUrl?>kids-wear/kurta-sets-for-girls.html?utm_source=google&amp;utm_medium=cpc&amp;utm_campaign=static%201&amp;utm_content=19feb"><span> Kurtas For Girls </span></a>|
                     <a class="utm_class" href="<?=$baseUrl?>kids-wear/lehengas.html?utm_source=google&amp;utm_medium=cpc&amp;utm_campaign=static%201&amp;utm_content=19feb"><span> Lehengas </span></a>|
                     <a class="utm_class" href="<?=$baseUrl?>kids-wear/anarkalis.html?utm_source=google&amp;utm_medium=cpc&amp;utm_campaign=static%201&amp;utm_content=19feb"><span> Anarkalis </span></a>|
                     <a class="utm_class" href="<?=$baseUrl?>kids-wear/sherwanis.html?utm_source=google&amp;utm_medium=cpc&amp;utm_campaign=static%201&amp;utm_content=19feb"><span> Sherwanis </span></a>|
                     <a class="utm_class" href="<?=$baseUrl?>kids-wear/kurta-sets-for-boys.html?utm_source=google&amp;utm_medium=cpc&amp;utm_campaign=static%201&amp;utm_content=19feb"><span> Kurtas For Boys </span></a>|
                     <a class="utm_class" href="<?=$baseUrl?>kids-wear/bandi-set.html?utm_source=google&amp;utm_medium=cpc&amp;utm_campaign=static%201&amp;utm_content=19feb"><span> Bandi Sets </span></a>|
                     <a class="utm_class" href="<?=$baseUrl?>kids-wear/kids-accessories.html?utm_source=google&amp;utm_medium=cpc&amp;utm_campaign=static%201&amp;utm_content=19feb"><span> Kids Accessories </span></a>|
                     <a class="utm_class" href="<?=$baseUrl?>kids-wear.html?themeFilter=6045"><span> Ethnic </span></a>|
                     <a class="utm_class" href="<?=$baseUrl?>kids-wear.html?themeFilter=6044"><span> Contemporary </span></a>
                  </p>
                  <div class="txt-heading">Top Designer Jewelry Categories</div>
                  <p class="footer-paragraph"> 
                     <a class="utm_class" href="<?=$baseUrl?>jewelry.html?themeFilter=6045"><span> Ethnic </span></a>|
                     <a class="utm_class" href="<?=$baseUrl?>jewelry.html?themeFilter=6044"><span> Contemporary </span></a>|
                     <a class="utm_class" href="<?=$baseUrl?>jewelry.html?utm_source=google&utm_medium=cpc&utm_campaign=static%201&utm_content=19feb"><span> All Jewelry </span></a>|
                     <a class="utm_class" href="<?=$baseUrl?>jewelry/earrings.html?utm_source=google&utm_medium=cpc&utm_campaign=static%201&utm_content=19feb"><span> Earrings </span></a>|
                     <a class="utm_class" href="<?=$baseUrl?>jewelry/necklaces.html?utm_source=google&utm_medium=cpc&utm_campaign=static%201&utm_content=19feb"><span> Necklaces </span></a>|
                     <a class="utm_class" href="<?=$baseUrl?>jewelry/rings.html?utm_source=google&utm_medium=cpc&utm_campaign=static%201&utm_content=19feb"><span> Rings </span></a>|
                     <a class="utm_class" href="<?=$baseUrl?>jewelry/hair-accessories/tikkas-and-passas.html?utm_source=google&utm_medium=cpc&utm_campaign=static%201&utm_content=19feb"><span> Tikkas &amp; Passas </span></a>|
                     <a class="utm_class" href="<?=$baseUrl?>jewelry/bangles-bracelets.html?utm_source=google&utm_medium=cpc&utm_campaign=static%201&utm_content=19feb"><span> Bangles &amp; Bracelets </span></a>|
                     <a class="utm_class" href="<?=$baseUrl?>jewelry/brooches.html?utm_source=google&utm_medium=cpc&utm_campaign=static%201&utm_content=19feb"><span> Brooches </span></a>|
                     <a class="utm_class" href="<?=$baseUrl?>jewelry/nose-rings.html?utm_source=google&utm_medium=cpc&utm_campaign=static%201&utm_content=19feb"><span> Nose rings </span></a>|
                     <a class="utm_class" href="<?=$baseUrl?>jewelry/hand-harness.html?utm_source=google&utm_medium=cpc&utm_campaign=static%201&utm_content=19feb"><span> Hand harness </span></a>|
                     <a class="utm_class" href="<?=$baseUrl?>jewelry/fine-jewelry.html?utm_source=google&utm_medium=cpc&utm_campaign=static%201&utm_content=19feb"><span> Fine Jewelry </span></a>
                  </p>
                  <div class="txt-heading">Designer Wedding Special Outfits</div>
                  <p class="footer-paragraph"> 
                     <a class="utm_class" href="<?=$baseUrl?>wedding.html?firstAttemptedFilter=categoryFilter&amp;categoryFilter=3127&amp;utm_source=google&amp;utm_medium=cpc&amp;utm_campaign=static%201&amp;utm_content=19feb"><span> All Clothing </span></a>|
                     <a class="utm_class" href="<?=$baseUrl?>wedding/womens-clothing/lehengas.html?utm_source=google&amp;utm_medium=cpc&amp;utm_campaign=static%201&amp;utm_content=19feb"><span> Lehengas </span></a>|
                     <a class="utm_class" href="<?=$baseUrl?>wedding/womens-clothing/anarkalis-kurtas.html?utm_source=google&amp;utm_medium=cpc&amp;utm_campaign=static%201&amp;utm_content=19feb"><span> Anarkalis and Kurtas </span></a>|
                     <a class="utm_class" href="<?=$baseUrl?>wedding/womens-clothing/saris.html?utm_source=google&amp;utm_medium=cpc&amp;utm_campaign=static%201&amp;utm_content=19feb"><span> Saris </span></a>|
                     <a class="utm_class" href="<?=$baseUrl?>wedding/womens-clothing/gowns.html?utm_source=google&amp;utm_medium=cpc&amp;utm_campaign=static%201&amp;utm_content=19feb"><span> Gowns </span></a>|
                     <a class="utm_class" href="<?=$baseUrl?>wedding/womens-clothing/anarkalis-kurtas/shararas.html?utm_source=google&amp;utm_medium=cpc&amp;utm_campaign=static%201&amp;utm_content=19feb"><span> Sharara Sets </span></a>|
                     <a class="utm_class" href="<?=$baseUrl?>wedding/womens-clothing/jackets-and-capes.html?utm_source=google&amp;utm_medium=cpc&amp;utm_campaign=static%201&amp;utm_content=19feb"><span> Jackets and Capes </span></a>|
                     <a class="utm_class" href="<?=$baseUrl?>wedding/men/sherwanis.html?utm_source=google&amp;utm_medium=cpc&amp;utm_campaign=static%201&amp;utm_content=19feb"><span> Sherwanis </span></a>|
                     <a class="utm_class" href="<?=$baseUrl?>wedding/men/bandi-sets.html?utm_source=google&amp;utm_medium=cpc&amp;utm_campaign=static%201&amp;utm_content=19feb"><span> Bandi Sets </span></a>|
                     <a class="utm_class" href="<?=$baseUrl?>wedding/men/bandhgalas.html?utm_source=google&amp;utm_medium=cpc&amp;utm_campaign=static%201&amp;utm_content=19feb"><span> Bandhgalas </span></a>
                  </p>
                  <div class="txt-heading">Discover The New In Collection</div>
                  <p class="footer-paragraph"> 
                     <a class="utm_class" href="<?=$baseUrl?>new-in.html?firstAttemptedFilter=calenderFilter&amp;calenderFilter=6204"><span> This Week </span></a>|
                     <a class="utm_class" href="<?=$baseUrl?>new-in.html?firstAttemptedFilter=calenderFilter&amp;calenderFilter=6205"><span> This Month </span></a>|
                     <a class="utm_class" href="<?=$baseUrl?>new-designers.html"><span> New Designers </span></a>|
                     <a class="utm_class" href="<?=$baseUrl?>new-in.html?firstAttemptedFilter=acoeditFilter&amp;acoeditFilter=6219"><span> Top Finds </span></a>|
                     <a class="utm_class" href="<?=$baseUrl?>new-in.html?firstAttemptedFilter=acoeditFilter&amp;acoeditFilter=6208"><span> Exclusive </span></a>|
                     <a class="utm_class" href="<?=$baseUrl?>new-in.html?themeFilter=6045"><span> Ethnic </span></a>|
                     <a class="utm_class" href="<?=$baseUrl?>new-in.html?themeFilter=6044"><span> Contemporary </span></a>
                  </p>
                  <div class="txt-heading">Explore Our Accessories</div>
                  <p class="footer-paragraph"> 
                     <a class="utm_class" href="<?=$baseUrl?>accessories.html?themeFilter=6045"><span> Ethnic </span></a>|
                     <a class="utm_class" href="<?=$baseUrl?>accessories.html?themeFilter=6044"><span> Contemporary </span></a>|
                     <a class="utm_class" href="<?=$baseUrl?>accessories.html?utm_source=google&amp;utm_medium=cpc&amp;utm_campaign=static%201&amp;utm_content=19feb"><span> All Accessories </span></a>|
                     <a class="utm_class" href="<?=$baseUrl?>accessories/bags.html?utm_source=google&amp;utm_medium=cpc&amp;utm_campaign=static%201&amp;utm_content=19feb"><span> Bags </span></a>|
                     <a class="utm_class" href="<?=$baseUrl?>accessories/belts.html?utm_source=google&amp;utm_medium=cpc&amp;utm_campaign=static%201&amp;utm_content=19feb"><span> Belts </span></a>|
                     <a class="utm_class" href="<?=$baseUrl?>accessories/scarves-and-stoles.html?utm_source=google&amp;utm_medium=cpc&amp;utm_campaign=static%201&amp;utm_content=19feb"><span> Scarves &amp; Stoles </span></a>|
                     <a class="utm_class" href="<?=$baseUrl?>accessories/shoes.html?utm_source=google&amp;utm_medium=cpc&amp;utm_campaign=static%201&amp;utm_content=19feb"><span> Shoes </span></a>|
                     <a class="utm_class" href="<?=$baseUrl?>men.html?firstAttemptedFilter=categoryFilter&amp;categoryFilter=3625&amp;utm_source=google&amp;utm_medium=cpc&amp;utm_campaign=static%201&amp;utm_content=19feb"><span> Brooches </span></a>|
                     <a class="utm_class" href="<?=$baseUrl?>men.html?firstAttemptedFilter=categoryFilter&amp;categoryFilter=2609&amp;utm_source=google&amp;utm_medium=cpc&amp;utm_campaign=static%201&amp;utm_content=19feb"><span> Cufflinks </span></a>|
                     <a class="utm_class" href="<?=$baseUrl?>men.html?firstAttemptedFilter=categoryFilter&amp;categoryFilter=4138&amp;utm_source=google&amp;utm_medium=cpc&amp;utm_campaign=static%201&amp;utm_content=19feb"><span> Lapel Pins </span></a>|
                     <a class="utm_class" href="<?=$baseUrl?>men.html?firstAttemptedFilter=categoryFilter&amp;categoryFilter=1714&amp;utm_source=google&amp;utm_medium=cpc&amp;utm_campaign=static%201&amp;utm_content=19feb"><span> Men's Shoes</span></a>
                  </p>
                  <div class="txt-heading">Designer Wear For All Your Special Occasions</div>
                  <p class="footer-paragraph"> 
                     <a class="utm_class" href="<?=$baseUrl?>bestsellers.html?firstAttemptedFilter=occasionFilter&amp;occasionFilter=6766"><span> Bridesmaid </span></a>|
                     <a class="utm_class" href="<?=$baseUrl?>bestsellers.html?firstAttemptedFilter=occasionFilter&amp;occasionFilter=6053"><span> Cocktail </span></a>|
                     <a class="utm_class" href="<?=$baseUrl?>bestsellers.html?firstAttemptedFilter=occasionFilter&amp;occasionFilter=6052"><span> Engagement </span></a>|
                     <a class="utm_class" href="<?=$baseUrl?>bestsellers.html?firstAttemptedFilter=occasionFilter&amp;occasionFilter=6051"><span> Festive </span></a>|
                     <a class="utm_class" href="<?=$baseUrl?>bestsellers.html?firstAttemptedFilter=occasionFilter&amp;occasionFilter=6050"><span> Mehendi &amp; Haldi </span></a>|
                     <a class="utm_class" href="<?=$baseUrl?>bestsellers.html?firstAttemptedFilter=occasionFilter&amp;occasionFilter=6234"><span> Party </span></a>|
                     <a class="utm_class" href="<?=$baseUrl?>bestsellers.html?firstAttemptedFilter=occasionFilter&amp;occasionFilter=6231"><span> Puja </span></a>|
                     <a class="utm_class" href="<?=$baseUrl?>bestsellers.html?firstAttemptedFilter=occasionFilter&amp;occasionFilter=6049"><span> Reception </span></a>|
                     <a class="utm_class" href="<?=$baseUrl?>bestsellers.html?firstAttemptedFilter=occasionFilter&amp;occasionFilter=6048"><span> Resort </span></a>|
                     <a class="utm_class" href="<?=$baseUrl?>bestsellers.html?firstAttemptedFilter=occasionFilter&amp;occasionFilter=6047"><span> Sangeet </span></a>|
                     <a class="utm_class" href="<?=$baseUrl?>bestsellers.html?firstAttemptedFilter=occasionFilter&amp;occasionFilter=6046"><span> Wedding </span></a>
                  </p>
                  <div class="txt-heading">Check Out Aashni + Co’s Special Edits</div>
                  <p class="footer-paragraph">
                     <a class="utm_class" href="<?=$baseUrl?>bestsellers.html?firstAttemptedFilter=acoeditFilter&amp;acoeditFilter=6266"><span> Belted Sarees </span></a>|
                     <a class="utm_class" href="<?=$baseUrl?>bestsellers.html?firstAttemptedFilter=acoeditFilter&amp;acoeditFilter=6267"><span> Bestsellers </span></a>|
                     <a class="utm_class" href="<?=$baseUrl?>bestsellers.html?firstAttemptedFilter=acoeditFilter&amp;acoeditFilter=6268"><span> Cotton Kurtas </span></a>|
                     <a class="utm_class" href="<?=$baseUrl?>bestsellers.html?firstAttemptedFilter=acoeditFilter&amp;acoeditFilter=6219"><span> Cult Finds </span></a>|
                     <a class="utm_class" href="<?=$baseUrl?>bestsellers.html?firstAttemptedFilter=acoeditFilter&amp;acoeditFilter=6269"><span> Easy Breezy Kurtas </span></a>|
                     <a class="utm_class" href="<?=$baseUrl?>bestsellers.html?firstAttemptedFilter=acoeditFilter&amp;acoeditFilter=6270"><span> Embellished Tops </span></a>|
                     <a class="utm_class" href="<?=$baseUrl?>bestsellers.html?firstAttemptedFilter=acoeditFilter&amp;acoeditFilter=6208"><span> Exclusive </span></a>|
                     <a class="utm_class" href="<?=$baseUrl?>bestsellers.html?firstAttemptedFilter=acoeditFilter&amp;acoeditFilter=6761"><span> Festive Kurtas </span></a>|
                     <a class="utm_class" href="<?=$baseUrl?>bestsellers.html?firstAttemptedFilter=acoeditFilter&amp;acoeditFilter=6211"><span> Festive Potlis </span></a>|
                     <a class="utm_class" href="<?=$baseUrl?>bestsellers.html?firstAttemptedFilter=acoeditFilter&amp;acoeditFilter=6271"><span> Floral Sarees </span></a>|
                     <a class="utm_class" href="<?=$baseUrl?>bestsellers.html?firstAttemptedFilter=acoeditFilter&amp;acoeditFilter=6223"><span> Heritage Weaves </span></a>|
                     <a class="utm_class" href="<?=$baseUrl?>bestsellers.html?firstAttemptedFilter=acoeditFilter&amp;acoeditFilter=6225"><span> Kurtas Under $500 </span></a>|
                     <a class="utm_class" href="<?=$baseUrl?>bestsellers.html?firstAttemptedFilter=acoeditFilter&amp;acoeditFilter=6465"><span> Lehengas Under $2000 </span></a>|
                     <a class="utm_class" href="<?=$baseUrl?>bestsellers.html?firstAttemptedFilter=acoeditFilter&amp;acoeditFilter=6218"><span> Off The Runway </span></a>|
                     <a class="utm_class" href="<?=$baseUrl?>bestsellers.html?firstAttemptedFilter=acoeditFilter&amp;acoeditFilter=6273"><span> Peplum Tops </span></a>|
                     <a class="utm_class" href="<?=$baseUrl?>bestsellers.html?firstAttemptedFilter=acoeditFilter&amp;acoeditFilter=6213"><span> Ruffle Lehengas </span></a>|
                     <a class="utm_class" href="<?=$baseUrl?>bestsellers.html?firstAttemptedFilter=acoeditFilter&amp;acoeditFilter=6209"><span> Sustainable Edit </span></a>|
                     <a class="utm_class" href="<?=$baseUrl?>bestsellers.html?firstAttemptedFilter=acoeditFilter&amp;acoeditFilter=6275"><span> The Summer Edit </span></a>|
                     <a class="utm_class" href="<?=$baseUrl?>bestsellers.html?firstAttemptedFilter=acoeditFilter&amp;acoeditFilter=6276"><span> White Tops </span></a>|
                     <a class="utm_class" href="<?=$baseUrl?>sale.html"><span> Sale </span></a>|
                     <a class="utm_class" href="<?=$baseUrl?>ready-to-ship.html"><span> Ready To Ship</span></a>
                  </p>
                  <div class="txt-heading">We Ship Internationally</div>
                  <p class="footer-paragraph">United Kingdom (UK) | United States of America (USA) | India | Germany | Australia | Canada | Japan | Argentina | Malaysia | Madagascar | Mexico | Morocco | Nepal | Russia | Saudi Arabia | Singapore | South Africa | Sri Lanka | Switzerland | Thailand | United Arab Emirates (UAE) | Vietnam &amp; many other countries</p>
               </div>
            </div>
         </div>
         <div class="bottom-footer">
            <div class="bottom-footer-container">
               <div class="bottom-row">
                  <div class="contact-us-footer-wrap">
                     <div class=" contact-us-footer">
                        <div class="links-head">Company</div>
                        <ul class="link-footer">
                           <li><a class="link-txt" href="<?=$baseUrl?>about">About Us</a></li>
                           <li><a class="link-txt" href="<?=$baseUrl?>contacts">Customer Care</a></li>
                           <li><a class="link-txt" href="<?=$baseUrl?>terms-worldwide.html">Terms & conditions for clients outside India</a></li>
                           <li><a class="link-txt" href="<?=$baseUrl?>terms-within-india.html"> Terms & conditions for clients within India </a></li>
                           <li><a class="link-txt" href="<?=$baseUrl?>privacy.html"> Privacy and Cookies </a></li>
                        </ul>
                     </div>
                  </div>
                  <div class="contact-us-footer-wrap info-wrap">
                     <div class="contact-us-footer ">
                        <div class="links-head">Information</div>
                        <ul class="link-footer">
                           <li><a class="link-txt" href="<?=$baseUrl?>returns-and-exchanges.html">Returns and Exchanges</a></li>
                           <li><a class="link-txt" href="<?=$baseUrl?>store-policies.html">Store Policies</a></li>
                           <li><a class="link-txt" href="<?=$baseUrl?>shipping">Shipping Options</a></li>
                           <li><a class="link-txt" href="<?=$baseUrl?>faq"> FAQ's </a></li>
                           <li><a class="link-txt" href="#"> How to Measure </a></li>
                        </ul>
                     </div>
                  </div>
                  <div class="contact-us-footer-wrap social-wrp">
                     <div class="contact-us-footer ">
                        <div class="links-head">Social</div>
                        <ul class="link-footer">
                           <li><a class="link-txt" href="https://www.facebook.com/pages/Aashni-Co-Official/417895134941609">Facebook</a></li>
                           <li><a class="link-txt" href="https://twitter.com/aashniuk">Twitter</a></li>
                           <li><a class="link-txt" href="https://www.instagram.com/aashniandco/">Instagram</a></li>
                           <li><a class="link-txt" href="https://in.pinterest.com/aashninco/"> Pinterest </a></li>
                        </ul>
                     </div>
                  </div>
               </div>
               <div class="bottom-row-two">
                  <div class="col-footer-social">
                     <div class="address">©2024 Aashni + Co</div>
                  </div>
                  <div class="col-footer-social">
                     <ul class="social-link">
                        <li><a href="https://www.facebook.com/pages/Aashni-Co-Official/417895134941609"><span class="fa fa-facebook"></span></a></li>
                        <li><a href="https://twitter.com/aashniuk"><span class="fa fa-twitter"></span></a></li>
                        <li><a href="https://www.instagram.com/aashniandco/"><span class="fa fa-instagram"></span></a></li>
                        <li><a href="https://in.pinterest.com/aashninco/"><span class="fa fa-pinterest"></span></a></li>
                     </ul>
                  </div>
               </div>
            </div>
         </div>
      </div>
	    <script src="<?=$baseUrl?>pub/static/frontend/Mgs/ethan/en_US/MGS_Mpanel/js/slick.js" crossorigin="anonymous"></script>
		<script src="<?=$baseUrl?>pub/static/frontend/Mgs/ethan/en_US/MGS_Mpanel/js/slick.min.js" crossorigin="anonymous"></script>
		<script src="<?=$baseUrl?>pub/static/frontend/Mgs/ethan/en_US/MGS_Mpanel/js/homepage_custom.min.js?v=<?=$jsVersion?>" crossorigin="anonymous"></script>
    
    <!-- Organization Schema (To be updated on all pages of website):-->
    <script type="application/ld+json">
      {
        "@context": "https://schema.org",
        "@type": "Organization",
        "name": "Aashni and Co",
        "alternateName": "Aashni + Co",
        "url": "https://aashniandco.com/",
        "logo": "https://d3hqqhbe1avk3m.cloudfront.net/logo/stores/1/aashniandco.png",
      "description": "Aashni + Co pioneers the most desirable edit in contemporary Indian high fashion.",
      "address": "125 Ledbury Road, London W11 2AQ",
        "contactPoint": [{
          "@type": "ContactPoint",
          "telephone": "+91- 8375036648",
          "contactType": "customer service",
          "areaServed": "IN"
        },{
          "@type": "ContactPoint",
          "telephone": "+44 755 728 9871",
          "contactType": "technical support",
          "areaServed": "GB"
      },{
      "@type": "ContactPoint",
          "email": "customercare@aashniandco.com",
          "contactType": "customer service",
          "areaServed": "IN"
        }],
        "sameAs": [
          "https://www.facebook.com/pages/Aashni-Co-Official/417895134941609",
          "https://twitter.com/aashniuk",
          "https://www.instagram.com/aashniandco/"
        ]
      }
    </script>

    <!--Local Business: Type – Local Business (To be updated on all pages)-->
    <script type="application/ld+json">
      {
        "@context": "https://schema.org",
        "@type": "LocalBusiness",
        "name": "Aashni and Co",
        "image": "https://d3hqqhbe1avk3m.cloudfront.net/logo/stores/1/aashniandco.png",
        "@id": "",
        "url": "https://aashniandco.com",
        "telephone": "+44 207 985 0155",
        "address": {
          "@type": "PostalAddress",
          "streetAddress": "125 Ledbury Road",
          "addressLocality": "London",
          "postalCode": "W11 2AQ",
          "addressCountry": "GB"
        },
        "openingHoursSpecification": [{
          "@type": "OpeningHoursSpecification",
          "dayOfWeek": [
            "Monday",
            "Tuesday",
            "Wednesday",
            "Thursday",
            "Friday",
            "Saturday"
          ],
          "opens": "10:00",
          "closes": "19:00"
        },{
          "@type": "OpeningHoursSpecification",
          "dayOfWeek": "Sunday",
          "opens": "12:00",
          "closes": "18:00"
        }],
        "sameAs": [
          "ttps://www.facebook.com/pages/Aashni-Co-Official/417895134941609",
          "https://twitter.com/aashniuk",
          "https://www.instagram.com/aashniandco/"
        ]
      }
    </script>


    <!-- Local Business: Type – Store (To be updated on all pages)-->
    <script type="application/ld+json">
      {
        "@context": "https://schema.org",
        "@type": "Store",
        "name": "Aashni and Co",
        "image": "https://d3hqqhbe1avk3m.cloudfront.net/logo/stores/1/aashniandco.png",
        "@id": "",
        "url": "https://aashniandco.com",
        "telephone": "+44 207 985 0155",
        "address": {
          "@type": "PostalAddress",
          "streetAddress": "Ledbury Road",
          "addressLocality": "London",
          "postalCode": "W11 2AQ",
          "addressCountry": "GB"
        },
        "openingHoursSpecification": [{
          "@type": "OpeningHoursSpecification",
          "dayOfWeek": [
            "Monday",
            "Tuesday",
            "Wednesday",
            "Thursday",
            "Friday",
            "Saturday"
          ],
          "opens": "10:00",
          "closes": "19:00"
        },{
          "@type": "OpeningHoursSpecification",
          "dayOfWeek": "Sunday",
          "opens": "12:00",
          "closes": "18:00"
        }],
        "sameAs": [
          "ttps://www.facebook.com/pages/Aashni-Co-Official/417895134941609",
          "https://twitter.com/aashniuk",
          "https://www.instagram.com/aashniandco/"
        ]
      }
    </script> 
    </body>
</html>