<style>
@import url('https://fonts.googleapis.com/css2?family=Prata&display=swap');
body {
	margin: 0;
	padding:0px;
	color: #000;
	background: #fff;
}
 
.container22 {
	width: 100%;
}
#mms table { text-align:center;
	margin: 0;
	border-collapse: collapse;
}
#mms td, th {
	padding:5px 8px;  
	border: 1px solid #999;
}
#mms .table-container-outer {
	position: relative;
}
#mms .table-container {
	width: 100%;
	overflow-y: auto;
	_overflow: auto;
	margin: 0px;
}
#mms .table-container::-webkit-scrollbar {
 -webkit-appearance: none;
 width: 14px;
 height: 14px;
}
#mms .table-container::-webkit-scrollbar-thumb {
 border-radius: 0px;
 border: 1px solid #fff;
 background-color: rgba(0, 0, 0, .3);
}
#mms.table-container-fade {
	position: absolute;
	right: 0;
	width: 30px;
	height: 100%;
	background-image: -webkit-linear-gradient(0deg, rgba(255, 255, 255, .5), #fff);
	background-image: -moz-linear-gradient(0deg, rgba(255, 255, 255, .5), #fff);
	background-image: -ms-linear-gradient(0deg, rgba(255, 255, 255, .5), #fff);
	background-image: -o-linear-gradient(0deg, rgba(255, 255, 255, .5), #fff);
	background-image: linear-gradient(0deg, rgba(255, 255, 255, .5), #fff);
}
.table_titles{ padding-top:20px; border-top:2px #000 solid;}
 .table_titles h2{font-family: 'Prata', serif; font-size: 20px;
padding-bottom: 8px;}
 .table_titles p{  serif; font-size:17px;}
@media only screen and (max-width: 600px) {
	.table_titles{ text-align:center;}
	
}
</style>

<div id="mms" class="container22">
	<div class="table_titles">
    <h2>AASHNI+CO - Boy's Measurement Chart</h2>
  </div>
  <div class="table-container-outer">
    <div class="table-container-fade"></div>
    <div class="table-container">
      <div style="position: absolute; left:0PX; top:0px;">
      
      <table>
        <tbody><tr>
          <td style="background:#eee !important;">Size</td>
          <th>Chest Round (inches)</th>
          <th>Waist Round (inches)</th>
          <th>Kurta Length (inches)</th>
          <th>Jacket Length (inches)</th>
          <th>Pant Length (inches)</th>
        </tr>
        <tr>
          <td style="background:#eee;">3-6 MONTHS</td>
          <td>17</td>
          <td>20</td>
          <td>14</td>
          <td>10</td>
          <td>15</td>
        </tr>
        <tr>
          <td style="background:#eee;">6-12 MONTHS</td>
          <td>18</td>
          <td>21</td>
          <td>16</td>
          <td>12</td>
          <td>15</td>
        </tr>
        <tr>
          <td style="background:#eee;">1-2 YEARS</td>
          <td>19</td>
          <td>22</td>
          <td>17</td>
          <td>13</td>
          <td>16</td>
        </tr>
        <tr>
          <td style="background:#eee;">2-3 YEARS</td>
          <td>21</td>
          <td>23</td>
          <td>20</td>
          <td>14</td>
          <td>18</td>
        </tr>
        <tr>
          <td style="background:#eee;">3-4 YEARS</td>
          <td>22</td>
          <td>24</td>
          <td>23</td>
          <td>15</td>
          <td>20</td>
        </tr>
        <tr>
          <td style="background:#eee;">4-5 YEARS</td>
          <td>23</td>
          <td>25</td>
          <td>24</td>
          <td>16</td>
          <td>22.5</td>
        </tr>
        <tr>
          <td style="background:#eee;">5-6 YEARS</td>
          <td>25.5</td>
          <td>26</td>
          <td>26</td>
          <td>17</td>
          <td>25</td>
        </tr>
        <tr>
          <td style="background:#eee;">6-7 YEARS</td>
          <td>27</td>
          <td>27</td>
          <td>27</td>
          <td>18</td>
          <td>27.5</td>
        </tr>
        <tr>
          <td style="background:#eee;">7-8 YEARS</td>
          <td>27</td>
          <td>28</td>
          <td>29</td>
          <td>19</td>
          <td>30</td>
        </tr>
        <tr>
          <td style="background:#eee;">8-9 YEARS</td>
          <td>28</td>
          <td>28</td>
          <td>30</td>
          <td>20</td> 
          <td>31</td> 
        </tr>
        <tr>
          <td style="background:#eee;">9-10 YEARS</td>
          <td>28</td>
          <td>29</td>
          <td>31</td>
          <td>21</td>
          <td>32.5</td>
        </tr>
        <tr>
          <td style="background:#eee;">10-11YEARS</td>
          <td>29</td>
          <td>29</td>
          <td>33</td>
          <td>22</td>
          <td>33</td>
        </tr>
        <tr>
          <td style="background:#eee;">11-12 YEARS</td>
          <td>29</td>
          <td>30</td>
          <td>33</td>
          <td>23</td>
          <td>33.5</td>
        </tr>
        <tr>
          <td style="background:#eee;">12-13 YEARS</td>
          <td>30</td>
          <td>30</td>
          <td>34</td>
          <td>24</td>
          <td>34</td>
        </tr>
        <tr>
          <td style="background:#eee;">13-14 YEARS</td>
          <td>31</td>
          <td>31</td>
          <td>35</td>
          <td>25</td>
          <td>34</td>
        </tr>
        <tr>
          <td style="background:#eee;">14-15 YEARS</td>
          <td>32</td>
          <td>31</td>
          <td>36</td>
          <td>26</td>
          <td>36</td>
        </tr>
        <tr>
          <td style="background:#eee;">15-16 YEARS</td>
          <td>33</td>
          <td>31</td>
          <td>37</td>
          <td>27</td>
          <td>37</td>
        </tr>
      </tbody></table>
    </div>
  </div>
</div>
</div>


 

