<?php $product = $block->getProduct(); ?>
<span class = "pdp-tab-title" >Composition :</span>
<span class = "pdp-tab-content"><?php echo $product->getData('composition'); ?></span>
<span class = "pdp-tab-title" >Care :</span>
<span class = "pdp-tab-content"><?php echo $product->getData('care'); ?></span>
<?php /* ?><div class = "pdp-tab-title" >Disclaimer : </div>
<div class = "pdp-tab-content"><?php echo $product->getData('disclaimer'); ?></div>
<div class = "pdp-tab-title" >Delivery -: </div>
<div class = "pdp-tab-content"><?php echo $product->getData('delivery'); ?></div><?php */ ?>

