<!DOCTYPE html>
<!-- saved from url=(0045)https://orders.aashniandco.com/table/size/3.html -->
<html lang="en"><head><meta http-equiv="Content-Type" content="text/html; charset=UTF-8">

<title>Size guide</title> 
<meta name="viewport" content="width=device-width, minimum-scale=1, maximum-scale=1">
<style>
@import url('https://fonts.googleapis.com/css2?family=Prata&display=swap');
body {
	margin: 0;
	padding:0px;
	color: #000;
	background: #fff;
}
 
.container22 {
	width: 100%;
}
#mms table { text-align:center;
	margin: 0;
	border-collapse: collapse;
}
#mms td, th {
	padding:5px 8px;  
	border: 1px solid #999;
}
#mms .table-container-outer {
	position: relative;
}
#mms .table-container {
	width: 100%;
	overflow-y: auto;
	_overflow: auto;
	margin: 0px;
}
#mms .table-container::-webkit-scrollbar {
 -webkit-appearance: none;
 width: 14px;
 height: 14px;
}
#mms .table-container::-webkit-scrollbar-thumb {
 border-radius: 0px;
 border: 1px solid #fff;
 background-color: rgba(0, 0, 0, .3);
}
#mms.table-container-fade {
	position: absolute;
	right: 0;
	width: 30px;
	height: 100%;
	background-image: -webkit-linear-gradient(0deg, rgba(255, 255, 255, .5), #fff);
	background-image: -moz-linear-gradient(0deg, rgba(255, 255, 255, .5), #fff);
	background-image: -ms-linear-gradient(0deg, rgba(255, 255, 255, .5), #fff);
	background-image: -o-linear-gradient(0deg, rgba(255, 255, 255, .5), #fff);
	background-image: linear-gradient(0deg, rgba(255, 255, 255, .5), #fff);
}
.table_titles{ padding-top:20px; border-top:2px #000 solid;}
 .table_titles h2{font-family: 'Prata', serif; font-size: 20px;
padding-bottom: 8px;}
 .table_titles p{  serif; font-size:17px;}
@media only screen and (max-width: 600px) {
	.table_titles{ text-align:center;}
	
}
</style>
</head>
<body>
<div id="mms" class="container22">
	<div class="table_titles">
    	<h2>SIZE GUIDE</h2>
    </div>
  <div class="table-container-outer">
    <div class="table-container-fade"></div>
    <div class="table-container">
      <div style="width:0px; height:0px; position: absolute; left:0PX; top:0px;">
        <table id="size_contry" style="background:#fff; position:relative; text-align:left; z-index:1;">
          <tbody><tr>
            <td style="border-right:0px;">SIZE</td>
          </tr>
          <tr>
            <td style="border-right:0px;">NUMERICAL</td>
          </tr>
          <tr>
            <td style="border-right:0px;">UK</td>
          </tr>
          <tr>
            <td style="border-right:0px;">US</td>
          </tr>
          <tr>
            <td style="border-right:0px;">IT</td>
          </tr>
          <tr>
            <td style="border-right:0px;">FR</td>
          </tr>
          <tr>
            <td style="border-right:0px;"> DAN/GER</td>
          </tr>
          <tr>
            <td style="border-right:0px;"> RUSSIA</td>
          </tr>
          <tr>
            <td style="border-right:0px;">JAP</td>
          </tr>
          <tr>
            <td style="border-right:0px;"> AUS</td>
          </tr>
          <tr>
            <td style="border-right:0px;"> KOREA</td>
          </tr>
          <tr>
            <td style="border-right:0px;"> CHINA TOP </td>
          </tr>
          <tr>
            <td style="border-right:0px;"> CHINA&nbsp;BOTTOM&nbsp;&nbsp; </td>
          </tr>
        </tbody></table>
      </div>
      
      <table>
        <tbody><tr>
          <th style="background:#eee;">SIZE</th>
           <th>XXS </th>
          <th>XS </th>
          <th> S </th>
          <th> M </th>
          <th>M-L </th>
          <th> L </th>
          <th> XL</th>
        </tr>
        <tr>
          <td style="background:#eee;">NUMERICAL</td>
          <td></td>
          <td></td>
          <td>1</td>
          <td>2 </td>
          <td>2-3 </td>
          <td>3 </td>
          <td>4</td>
        </tr>
        <tr>
          <td style="background:#eee;">UK</td>
          <td>4 </td>
          <td>6</td>
          <td>8 </td>
          <td>10 </td>
          <td>12 </td>
          <td>14 </td>
          <td>16</td>
        </tr>
        <tr>
          <td style="background:#eee;">US</td>
          <td>0 </td>
          <td>2</td>
          <td>4 </td>
          <td>6 </td>
          <td>8 </td>
          <td>10 </td>
          <td>12</td>
        </tr>
        <tr>
          <td style="background:#eee;">IT</td>
          <td>36 </td>
          <td>38 </td>
          <td>40 </td>
          <td>42 </td>
          <td>44</td>
          <td>46 </td>
          <td>48</td>
        </tr>
        <tr>
          <td style="background:#eee;">FR</td>
          <td>32 </td>
          <td>34</td>
          <td>36 </td>
          <td>38 </td>
          <td>40 </td>
          <td>42</td>
          <td> 44</td>
        </tr>
        <tr>
          <td style="background:#eee;">DAN/GER</td>
          <td>30 </td>
          <td> 32</td>
          <td>34 </td>
          <td>36 </td>
          <td>38 </td>
          <td>40 </td>
          <td>42 </td>
        </tr>
        <tr>
          <td style="background:#eee;">RUSSIA</td>
          <td>38 </td>
          <td>40 </td>
          <td>42 </td>
          <td>44 </td>
          <td>46 </td>
          <td> 48 </td>
          <td> 50</td>
        </tr>
        <tr>
          <td style="background:#eee;">JAP </td>
          <td>3 </td>
          <td>5 </td>
          <td>7 </td>
          <td>9 </td>
          <td>11 </td>
          <td>13 </td>
          <td>15</td>
        </tr>
        <tr>
          <td style="background:#eee;">AUS </td>
          <td>4</td>
          <td>6 </td>
          <td>8 </td>
          <td>10 </td>
          <td>12 </td>
          <td>14 </td>
          <td>16</td>
        </tr>
        <tr>
          <td style="background:#eee;">KOREA </td>
          <td>- </td>
          <td>44 </td>
          <td>55 </td>
          <td>66 </td>
          <td> 77 </td>
          <td> 88 </td>
          <td> - </td>
            
        </tr>
        <tr>
          
          <td style="background:#eee;">CHINA TOP </td>
          <td>7155/76A </td>
          <td> 160/80A </td>
          <td> 7165/84A </td>
          <td>170/88A </td>
          <td>7175/92A </td>
          <td>180/96A </td>
          <td>180/96A </td>
            
        </tr>
        <tr>
          <td style="background:#eee;"> CHINA&nbsp;BOTTOM </td>
          <td> 155/64A </td>
          <td> 160/66A </td>
          <td> 165/68A </td>
          <td> 170/70A </td>
          <td> 175/72A </td>
          <td> 180/74A </td>
          <td> 185/76A </td>
            
        </tr>
      </tbody></table>
    </div>
  </div>
</div>


 
</body></html>
