
<style>
@import url('https://fonts.googleapis.com/css2?family=Prata&display=swap');
body {
	margin: 0;
	padding:0px;
	color: #000;
	background: #fff;
}
 
.container22 {
	width: 100%;
}
#mms table { text-align:center;
	margin: 0;
	border-collapse: collapse;
}
#mms td, th {
	padding:5px 8px;  
	border: 1px solid #999;
}
#mms .table-container-outer {
	position: relative;
}
#mms .table-container {
	width: 100%;
	overflow-y: auto;
	_overflow: auto;
	margin: 0px;
}
#mms .table-container::-webkit-scrollbar {
 -webkit-appearance: none;
 width: 14px;
 height: 14px;
}
#mms .table-container::-webkit-scrollbar-thumb {
 border-radius: 0px;
 border: 1px solid #fff;
 background-color: rgba(0, 0, 0, .3);
}
#mms.table-container-fade {
	position: absolute;
	right: 0;
	width: 30px;
	height: 100%;
	background-image: -webkit-linear-gradient(0deg, rgba(255, 255, 255, .5), #fff);
	background-image: -moz-linear-gradient(0deg, rgba(255, 255, 255, .5), #fff);
	background-image: -ms-linear-gradient(0deg, rgba(255, 255, 255, .5), #fff);
	background-image: -o-linear-gradient(0deg, rgba(255, 255, 255, .5), #fff);
	background-image: linear-gradient(0deg, rgba(255, 255, 255, .5), #fff);
}
.table_titles{ padding-top:20px; border-top:2px #000 solid;}
 .table_titles h2{font-family: 'Prata', serif; font-size: 20px;
padding-bottom: 8px;}
 .table_titles p{  serif; font-size:17px;}
@media only screen and (max-width: 600px) {
	.table_titles{ text-align:center;}
	
}
</style>

<div id="mms" class="container22">
  <div class="table_titles">
    <h2>AASHNI+CO - Kids's Footwear Measurement Chart</h2>
  </div>
  <div class="table-container-outer">
    <div class="table-container-fade"></div>
    <div class="table-container">
      <div style="width:100%; height:0px; position: absolute; left:0PX; top:0px;">
      
      <table>
        <tbody>
        <tr>
          <th style="background:#eee;">European Sizes</th>
          <td>23</td>
          <td>25</td>
          <td>27</td>
          <td>29</td>
          <td>31</td>
          <td>33</td>
        </tr>
        <tr>
          <th style="background:#eee;">Inches</th>
          <td>5.5"</td>
          <td>6"</td>
          <td>6.5"</td>
          <td>7"</td>
          <td>7.5"</td>
          <td>8"</td>
        </tr>
        <tr>
          <th style="background:#eee;">Cms</th>
          <td>14</td>
          <td>16</td>
          <td>17</td>
          <td>17.5</td>
          <td>19</td>
          <td>20</td>
        </tr>
        <tr>
          <th style="background:#eee;">Age Group</th>
          <td>1-2 years</td>
          <td>3 years</td>
          <td>4 years</td>
          <td>4-5 years</td>
          <td>6 years</td>
          <td>6-7 years</td>
        </tr>
      </tbody></table>
    </div>
  </div>
</div>
</div>


 

