<?php $product = $block->getProduct(); ?>
<div class = "pdp-tab-title" >Measurements :</div>
<div class = "pdp-tab-content" ><?php echo $product->getData('measurements'); ?></div>
<?php /* ?><div class = "pdp-tab-title" >Disclaimer :</div>
<div  class = "pdp-tab-content" ><?php echo $product->getData('disclaimer'); ?></div>
<div class = "pdp-tab-title" >Delivery</div>
<div class = "pdp-tab-content" ><?php echo $product->getData('delivery'); ?></div><?php */ ?>
