<style>
@import url('https://fonts.googleapis.com/css2?family=Prata&display=swap');
body {
	margin: 0;
	padding:0px;
	color: #000;
	background: #fff;
}
 
.container22 {
	width: 100%;
}
#mms table { text-align:center;
	margin: 0;
	border-collapse: collapse;
}
#mms td, th {
	padding:5px 8px;  
	border: 1px solid #999;
}
#mms .table-container-outer {
	position: relative;
}
#mms .table-container {
	width: 100%;
	overflow-y: auto;
	_overflow: auto;
	margin: 0px;
}
#mms .table-container::-webkit-scrollbar {
 -webkit-appearance: none;
 width: 14px;
 height: 14px;
}
#mms .table-container::-webkit-scrollbar-thumb {
 border-radius: 0px;
 border: 1px solid #fff;
 background-color: rgba(0, 0, 0, .3);
}
#mms.table-container-fade {
	position: absolute;
	right: 0;
	width: 30px;
	height: 100%;
	background-image: -webkit-linear-gradient(0deg, rgba(255, 255, 255, .5), #fff);
	background-image: -moz-linear-gradient(0deg, rgba(255, 255, 255, .5), #fff);
	background-image: -ms-linear-gradient(0deg, rgba(255, 255, 255, .5), #fff);
	background-image: -o-linear-gradient(0deg, rgba(255, 255, 255, .5), #fff);
	background-image: linear-gradient(0deg, rgba(255, 255, 255, .5), #fff);
}
.table_titles{ padding-top:20px; border-top:2px #000 solid;}
 .table_titles h2{font-family: 'Prata', serif; font-size: 20px;
padding-bottom: 8px;}
 .table_titles p{  serif; font-size:17px;}
@media only screen and (max-width: 600px) {
	.table_titles{ text-align:center;}
	
}
</style>

<div id="mms" class="container22">
	<div class="table_titles">
    <h2>AASHNI+CO - Men's Measurement Chart</h2>
  </div>
  <div class="table-container-outer">
    <div class="table-container-fade"></div>
    <div class="table-container">
      <table>
        <tbody><tr>
          <td style="background:#eee !important;">Size</td>
          <th>Chest (inches)</th>
          <th>Waist (inches)</th>
          <th>Neck (inches)</th>
          <th>Hip (inches)</th>
        </tr>
        <tr>
          <td style="background:#eee;">XS</td>
          <td>36</td>
          <td>28-30</td>
          <td>14</td>
          <td>36.5 - 38.5</td>
        </tr>
        <tr>
          <td style="background:#eee;">S</td>
          <td>38</td>
          <td>30-32</td>
          <td>15</td>
          <td>38.5 - 40.5</td>
        </tr>
        <tr>
          <td style="background:#eee;">M</td>
          <td>40</td>
          <td>32-34</td>
          <td>16</td>
          <td>40.5 - 41.5</td>
        </tr>
        <tr>
          <td style="background:#eee;">L</td>
          <td>42</td>
          <td>34-36</td>
          <td>17</td>
          <td>41.5 - 42.5</td>
        </tr>
        <tr>
          <td style="background:#eee;">XL</td>
          <td>44</td>
          <td>36-38</td>
          <td>18</td>
          <td>42.5 - 43.5</td>
        </tr>
        <tr>
          <td style="background:#eee;">XXL</td>
          <td>46</td>
          <td>38-40</td>
          <td>19</td>
          <td>43.5 - 44.5</td>
        </tr>
        <tr>
          <td style="background:#eee;">3XL</td>
          <td>48</td>
          <td>40-42</td>
          <td>20</td>
          <td>44.5 - 46.5</td>
        </tr>
        <tr>
          <td style="background:#eee;">4XL</td>
          <td>50</td>
          <td>42-44</td>
          <td>21</td>
          <td>46.5 - 48.5</td>
        </tr>
        <tr>
          <td style="background:#eee;">5XL</td>
          <td>52</td>
          <td>44-46</td>
          <td>22</td>
          <td>48.5 - 50.5</td>
        </tr>
        <tr>
          <td style="background:#eee;">6XL</td>
          <td>54</td>
          <td>46-48</td>
          <td>23</td>
          <td>50.5 - 52.5</td> 
        </tr>
      </tbody></table>
    </div>
  </div>
</div>