<style>
@import url('https://fonts.googleapis.com/css2?family=Prata&display=swap');
body {
	margin: 0;
	padding:0px;
	color: #000;
	background: #fff;
}
 
.container22 {
	width: 100%;
}
#mms table { text-align:center;
	margin: 0;
	border-collapse: collapse;
}
#mms td, th {
	padding:5px 8px;  
	border: 1px solid #999;
}
#mms .table-container-outer {
	position: relative;
}
#mms .table-container {
	width: 100%;
	overflow-y: auto;
	_overflow: auto;
	margin: 0px;
}
#mms .table-container::-webkit-scrollbar {
 -webkit-appearance: none;
 width: 14px;
 height: 14px;
}
#mms .table-container::-webkit-scrollbar-thumb {
 border-radius: 0px;
 border: 1px solid #fff;
 background-color: rgba(0, 0, 0, .3);
}
#mms.table-container-fade {
	position: absolute;
	right: 0;
	width: 30px;
	height: 100%;
	background-image: -webkit-linear-gradient(0deg, rgba(255, 255, 255, .5), #fff);
	background-image: -moz-linear-gradient(0deg, rgba(255, 255, 255, .5), #fff);
	background-image: -ms-linear-gradient(0deg, rgba(255, 255, 255, .5), #fff);
	background-image: -o-linear-gradient(0deg, rgba(255, 255, 255, .5), #fff);
	background-image: linear-gradient(0deg, rgba(255, 255, 255, .5), #fff);
}
.table_titles{ padding-top:20px; border-top:2px #000 solid;}
 .table_titles h2{font-family: 'Prata', serif; font-size: 20px;
padding-bottom: 8px;}
 .table_titles p{  serif; font-size:17px;}
@media only screen and (max-width: 600px) {
	.table_titles{ text-align:center;}
	
}
</style>

<div id="mms" class="container22">
	<div class="table_titles">
    <h2>AASHNI+CO - Belt's Measurement Chart</h2>
  </div>
  <div class="table-container-outer">
    <div class="table-container-fade"></div>
    <div class="table-container">
      <table>
        <tbody><tr>
          <th style="background:#eee !important;">Size</th>
          <th style="background:#eee !important;">Waist (inches)</th>
        </tr>
        <tr>
          <td>XS</td>
          <td>30</td>
        </tr>
        <tr>
          <td>S</td>
          <td>32</td>
        </tr>
        <tr>
          <td>M</td>
          <td>34</td>
        </tr>
        <tr>
          <td>L</td>
          <td>36</td>
        </tr>
        <tr>
          <td>XL</td>
          <td>38</td>
        </tr>
        <tr>
          <td>XXL</td>
          <td>40</td>
        </tr>
        <tr>
          <td>3XL</td>
          <td>42</td>
        </tr>
        <tr>
          <td>4XL</td>
          <td>44</td>
        </tr>
        <tr>
          <td>5XL</td>
          <td>46</td>
        </tr>
        <tr>
          <td>6XL</td>
          <td>48</td>
        </tr>
      </tbody></table>
    </div>
  </div>
</div>