<style>
@import url('https://fonts.googleapis.com/css2?family=Prata&display=swap');
body {
	margin: 0;
	padding:0px;
	color: #000;
	background: #fff;
}
.table_titles{ padding-top:20px; border-top:2px #000 solid;}
 .table_titles h2{font-family: 'Prata', serif; font-size: 20px;
padding-bottom: 8px;}
 .table_titles p{  serif; font-size:17px;}
 
 .container22 {
  width: 100%;
}
#mms table { text-align:center;
  margin: 0;
  border-collapse: collapse;
}
#mms td, th {
  padding:5px 8px;  
  border: 1px solid #999;
}
#mms .table-container-outer {
  position: relative;
}
#mms .table-container {
  width: 100%;
  overflow-y: auto;
  _overflow: auto;
  margin: 0px;
}
#mms .table-container::-webkit-scrollbar {
 -webkit-appearance: none;
 width: 14px;
 height: 14px;
}
#mms .table-container::-webkit-scrollbar-thumb {
 border-radius: 0px;
 border: 1px solid #fff;
 background-color: rgba(0, 0, 0, .3);
}
#mms.table-container-fade {
  position: absolute;
  right: 0;
  width: 30px;
  height: 100%;
  background-image: -webkit-linear-gradient(0deg, rgba(255, 255, 255, .5), #fff);
  background-image: -moz-linear-gradient(0deg, rgba(255, 255, 255, .5), #fff);
  background-image: -ms-linear-gradient(0deg, rgba(255, 255, 255, .5), #fff);
  background-image: -o-linear-gradient(0deg, rgba(255, 255, 255, .5), #fff);
  background-image: linear-gradient(0deg, rgba(255, 255, 255, .5), #fff);
}
@media only screen and (max-width: 600px) {
	.table_titles{ text-align:center;}
	
}
</style>

<div id="mms" class="container22">
	<div class="table_titles">
    	<h2>SIZE GUIDE</h2>
    </div>
  <div class="table-container-outer">
    <div class="table-container-fade"></div>
    <div class="table-container">
    
    <img src="https://aashniandco.com/pub/size/size_chart_footwear.jpg" style="width:100%;">
    
     <!-- <div style="width:0px; height:0px; position: absolute; left:0PX; top:0px;">
        <table style="background:#fff; border-right:1px #ccc solid;  position:relative; text-align:left; z-index:1;">
          <tr>
            <td style="border-right:0px;">SIZE</td>
          </tr>
          <tr>
            <td style="border-right:0px;">NUMERICAL</td>
          </tr>
          <tr>
            <td style="border-right:0px;">UK</td>
          </tr>
          <tr>
            <td style="border-right:0px;">US</td>
          </tr>
          <tr>
            <td style="border-right:0px;">IT</td>
          </tr>
          <tr>
            <td style="border-right:0px;">FR</td>
          </tr>
          <tr>
            <td style="border-right:0px;"> DAN/GER</td>
          </tr>
          <tr>
            <td style="border-right:0px;"> RUSSIA</td>
          </tr>
          <tr>
            <td style="border-right:0px;">JAP</td>
          </tr>
          <tr>
            <td style="border-right:0px;"> AUS</td>
          </tr>
          <tr>
            <td style="border-right:0px;"> KOREA</td>
          </tr>
          <tr>
            <td style="border-right:0px;"> CHINA TOP </td>
          </tr>
          <tr>
            <td style="border-right:0px;"> CHINA&nbsp;BOTTOM&nbsp;&nbsp; </td>
          </tr>
        </table>
      </div> -->
    <!--
    <h2  style="font-size: 18px;font-weight: 500; margin:15px 0px 5px 0px; "> Women's Sizing Chart </h2>
    <table style="width:100%">
    <tr style="background: #eee;">
          <th>UK</th>
           <th>EU </th>
          <th>US </th>
          <th> CM </th>
          
        </tr>
    
  <tr>
    <td align="center" valign="middle" style="border-bottom:1px #000 solid;"> 2.5 </td>
    <td align="center" valign="middle" style="border:1px #000 solid; border-width:0px 1px 1px 1px ;"> 35.5 </td>
    <td align="center" valign="middle" style="border-bottom:1px #000 solid;"> 4.5 </td>
    <td align="center" valign="middle" style="border:1px #000 solid; border-width:0px 1px 1px 1px ;">21 </td>
    
  </tr>
  
  <tr>
    <td align="center" valign="middle" style="border-bottom:1px #000 solid;"> 3 </td>
    <td align="center" valign="middle" style="border:1px #000 solid; border-width:0px 1px 1px 1px ;"> 36 </td>
    <td align="center" valign="middle" style="border-bottom:1px #000 solid;"> 5 </td>
    <td align="center" valign="middle" style="border:1px #000 solid; border-width:0px 1px 1px 1px ;">21.5 </td>
    
  </tr>
  
  
  <tr>
    <td align="center" valign="middle" style="border-bottom:1px #000 solid;"> 3.5 </td>
    <td align="center" valign="middle" style="border:1px #000 solid; border-width:0px 1px 1px 1px ;"> 36.5 </td>
    <td align="center" valign="middle" style="border-bottom:1px #000 solid;"> 5.5 </td>
    <td align="center" valign="middle" style="border:1px #000 solid; border-width:0px 1px 1px 1px ;">22 </td>
    
  </tr>
  
  <tr>
    <td align="center" valign="middle" style="border-bottom:1px #000 solid;"> 4 </td>
    <td align="center" valign="middle" style="border:1px #000 solid; border-width:0px 1px 1px 1px ;"> 37 </td>
    <td align="center" valign="middle" style="border-bottom:1px #000 solid;"> 6 </td>
    <td align="center" valign="middle" style="border:1px #000 solid; border-width:0px 1px 1px 1px ;">22.5 </td>
    
  </tr>
  
  <tr>
    <td align="center" valign="middle" style="border-bottom:1px #000 solid;"> 4.5 </td>
    <td align="center" valign="middle" style="border:1px #000 solid; border-width:0px 1px 1px 1px ;"> 37.5 </td>
    <td align="center" valign="middle" style="border-bottom:1px #000 solid;"> 6.5 </td>
    <td align="center" valign="middle" style="border:1px #000 solid; border-width:0px 1px 1px 1px ;">23 </td>
    
  </tr>
  
  
  <tr>
    <td align="center" valign="middle" style="border-bottom:1px #000 solid;"> 5 </td>
    <td align="center" valign="middle" style="border:1px #000 solid; border-width:0px 1px 1px 1px ;"> 38 </td>
    <td align="center" valign="middle" style="border-bottom:1px #000 solid;"> 7 </td>
    <td align="center" valign="middle" style="border:1px #000 solid; border-width:0px 1px 1px 1px ;">23.5 </td>
    
  </tr>
  
  
  <tr>
    <td align="center" valign="middle" style="border-bottom:1px #000 solid;"> 5.5 </td>
    <td align="center" valign="middle" style="border:1px #000 solid; border-width:0px 1px 1px 1px ;"> 38.5 </td>
    <td align="center" valign="middle" style="border-bottom:1px #000 solid;"> 7.5 </td>
    <td align="center" valign="middle" style="border:1px #000 solid; border-width:0px 1px 1px 1px ;"> 24 </td>
    
  </tr>
  
  <tr>
    <td align="center" valign="middle" style="border-bottom:1px #000 solid;"> 6 </td>
    <td align="center" valign="middle" style="border:1px #000 solid; border-width:0px 1px 1px 1px ;"> 39 </td>
    <td align="center" valign="middle" style="border-bottom:1px #000 solid;"> 8 </td>
    <td align="center" valign="middle" style="border:1px #000 solid; border-width:0px 1px 1px 1px ;"> 24.5 </td>
    
  </tr>
  
  <tr>
    <td align="center" valign="middle" style="border-bottom:1px #000 solid;"> 6.5 </td>
    <td align="center" valign="middle" style="border:1px #000 solid; border-width:0px 1px 1px 1px ;"> 39.5 </td>
    <td align="center" valign="middle" style="border-bottom:1px #000 solid;"> 8.5 </td>
    <td align="center" valign="middle" style="border:1px #000 solid; border-width:0px 1px 1px 1px ;"> 25 </td>
    
  </tr>
  
  <tr>
    <td align="center" valign="middle" style="border-bottom:1px #000 solid;"> 7 </td>
    <td align="center" valign="middle" style="border:1px #000 solid; border-width:0px 1px 1px 1px ;"> 40 </td>
    <td align="center" valign="middle" style="border-bottom:1px #000 solid;"> 9 </td>
    <td align="center" valign="middle" style="border:1px #000 solid; border-width:0px 1px 1px 1px ;"> 25.5 </td>
    
  </tr>
  
  <tr>
    <td align="center" valign="middle" style="border-bottom:1px #000 solid;"> 7.5 </td>
    <td align="center" valign="middle" style="border:1px #000 solid; border-width:0px 1px 1px 1px ;"> 40.5 </td>
    <td align="center" valign="middle" style="border-bottom:1px #000 solid;"> 9.5 </td>
    <td align="center" valign="middle" style="border:1px #000 solid; border-width:0px 1px 1px 1px ;"> 26 </td>
    
  </tr>
  
  
  <tr>
    <td align="center" valign="middle" style="border-bottom:1px #000 solid;"> 8 </td>
    <td align="center" valign="middle" style="border:1px #000 solid; border-width:0px 1px 1px 1px ;"> 41 </td>
    <td align="center" valign="middle" style="border-bottom:1px #000 solid;"> 10 </td>
    <td align="center" valign="middle" style="border:1px #000 solid; border-width:0px 1px 1px 1px ;"> 26.5 </td>
    
  </tr>
  
  <tr>
    <td align="center" valign="middle" style="border-bottom:1px #000 solid;"> 8.5 </td>
    <td align="center" valign="middle" style="border:1px #000 solid; border-width:0px 1px 1px 1px ;"> 41.5 </td>
    <td align="center" valign="middle" style="border-bottom:1px #000 solid;"> 10.5 </td>
    <td align="center" valign="middle" style="border:1px #000 solid; border-width:0px 1px 1px 1px ;"> 27 </td>
    
  </tr>
  
  <tr>
    <td align="center" valign="middle" style="border-bottom:1px #000 solid;"> 9 </td>
    <td align="center" valign="middle" style="border:1px #000 solid; border-width:0px 1px 1px 1px ;"> 42 </td>
    <td align="center" valign="middle" style="border-bottom:1px #000 solid;"> 11 </td>
    <td align="center" valign="middle" style="border:1px #000 solid; border-width:0px 1px 1px 1px ;"> 27.5 </td>
    
  </tr>
  
  <tr>
    <td align="center" valign="middle" style="border-bottom:1px #000 solid;"> 9.5 </td>
    <td align="center" valign="middle" style="border:1px #000 solid; border-width:0px 1px 1px 1px ;"> 42.5</td>
    <td align="center" valign="middle" style="border-bottom:1px #000 solid;"> 11.5 </td>
    <td align="center" valign="middle" style="border:1px #000 solid; border-width:0px 1px 1px 1px ;"> 28 </td>
    
  </tr>
  
  <tr>
    <td align="center" valign="middle" style="border-bottom:1px #000 solid;"> 10 </td>
    <td align="center" valign="middle" style="border:1px #000 solid; border-width:0px 1px 1px 1px ;"> 43</td>
    <td align="center" valign="middle" style="border-bottom:1px #000 solid;"> 12 </td>
    <td align="center" valign="middle" style="border:1px #000 solid; border-width:0px 1px 1px 1px ;"> 28.5 </td>
    
  </tr>
  
  <tr>
    <td align="center" valign="middle" style="border-bottom:1px #000 solid;"> 11 </td>
    <td align="center" valign="middle" style="border:1px #000 solid; border-width:0px 1px 1px 1px ;"> 44</td>
    <td align="center" valign="middle" style="border-bottom:1px #000 solid;"> 13 </td>
    <td align="center" valign="middle" style="border:1px #000 solid; border-width:0px 1px 1px 1px ;"> 29.5 </td>
    
  </tr>
  
  
  
    
    </table>
      <h2  style="font-size: 18px;font-weight: 500; margin:15px 0px 5px 0px;">Men's Sizing Chart</h2>
      <table style="width:100%">
         <tr style="background: #eee;">
          <th>UK</th>
           <th>EU </th>
          <th>US </th>
          <th> CM </th>
          
        </tr>
        <tr>
    <td align="center" valign="middle" style="border-bottom:1px #000 solid;"> 5.5 </td>
    <td align="center" valign="middle" style="border:1px #000 solid; border-width:0px 1px 1px 1px ;"> 39.5 </td>
    <td align="center" valign="middle" style="border-bottom:1px #000 solid;"> 6.5 </td>
    <td align="center" valign="middle" style="border:1px #000 solid; border-width:0px 1px 1px 1px ;">24 </td>
    
  </tr>
  
  <tr>
    <td align="center" valign="middle" style="border-bottom:1px #000 solid;"> 6 </td>
    <td align="center" valign="middle" style="border:1px #000 solid; border-width:0px 1px 1px 1px ;"> 40 </td>
    <td align="center" valign="middle" style="border-bottom:1px #000 solid;"> 7 </td>
    <td align="center" valign="middle" style="border:1px #000 solid; border-width:0px 1px 1px 1px ;">24.5 </td>
    
  </tr>
  
    <tr>
    <td align="center" valign="middle" style="border-bottom:1px #000 solid;"> 6.5 </td>
    <td align="center" valign="middle" style="border:1px #000 solid; border-width:0px 1px 1px 1px ;"> 40.5 </td>
    <td align="center" valign="middle" style="border-bottom:1px #000 solid;"> 7.5 </td>
    <td align="center" valign="middle" style="border:1px #000 solid; border-width:0px 1px 1px 1px ;">25 </td>
    
  </tr>
  
  <tr>
    <td align="center" valign="middle" style="border-bottom:1px #000 solid;"> 7 </td>
    <td align="center" valign="middle" style="border:1px #000 solid; border-width:0px 1px 1px 1px ;"> 41 </td>
    <td align="center" valign="middle" style="border-bottom:1px #000 solid;"> 8 </td>
    <td align="center" valign="middle" style="border:1px #000 solid; border-width:0px 1px 1px 1px ;">25.5 </td>
    
  </tr>
  
   <tr>
    <td align="center" valign="middle" style="border-bottom:1px #000 solid;"> 7.5 </td>
    <td align="center" valign="middle" style="border:1px #000 solid; border-width:0px 1px 1px 1px ;"> 41.5 </td>
    <td align="center" valign="middle" style="border-bottom:1px #000 solid;"> 8.5 </td>
    <td align="center" valign="middle" style="border:1px #000 solid; border-width:0px 1px 1px 1px ;">26 </td>
    
  </tr>
  
  
  <tr>
    <td align="center" valign="middle" style="border-bottom:1px #000 solid;"> 8 </td>
    <td align="center" valign="middle" style="border:1px #000 solid; border-width:0px 1px 1px 1px ;"> 42 </td>
    <td align="center" valign="middle" style="border-bottom:1px #000 solid;"> 9 </td>
    <td align="center" valign="middle" style="border:1px #000 solid; border-width:0px 1px 1px 1px ;">26.5 </td>
    
  </tr>
  
  <tr>
    <td align="center" valign="middle" style="border-bottom:1px #000 solid;"> 8.5 </td>
    <td align="center" valign="middle" style="border:1px #000 solid; border-width:0px 1px 1px 1px ;"> 42.5 </td>
    <td align="center" valign="middle" style="border-bottom:1px #000 solid;"> 9.5 </td>
    <td align="center" valign="middle" style="border:1px #000 solid; border-width:0px 1px 1px 1px ;">27 </td>
    
  </tr>
  
  <tr>
    <td align="center" valign="middle" style="border-bottom:1px #000 solid;"> 9 </td>
    <td align="center" valign="middle" style="border:1px #000 solid; border-width:0px 1px 1px 1px ;"> 43 </td>
    <td align="center" valign="middle" style="border-bottom:1px #000 solid;"> 10 </td>
    <td align="center" valign="middle" style="border:1px #000 solid; border-width:0px 1px 1px 1px ;">27.5 </td>
    
  </tr>
  
  <tr>
    <td align="center" valign="middle" style="border-bottom:1px #000 solid;"> 9.5 </td>
    <td align="center" valign="middle" style="border:1px #000 solid; border-width:0px 1px 1px 1px ;"> 43.5 </td>
    <td align="center" valign="middle" style="border-bottom:1px #000 solid;"> 10.5 </td>
    <td align="center" valign="middle" style="border:1px #000 solid; border-width:0px 1px 1px 1px ;">28 </td>
    
  </tr>
  
  <tr>
    <td align="center" valign="middle" style="border-bottom:1px #000 solid;"> 10 </td>
    <td align="center" valign="middle" style="border:1px #000 solid; border-width:0px 1px 1px 1px ;"> 44 </td>
    <td align="center" valign="middle" style="border-bottom:1px #000 solid;"> 11 </td>
    <td align="center" valign="middle" style="border:1px #000 solid; border-width:0px 1px 1px 1px ;">28.5 </td>
    
  </tr>
  
  <tr>
    <td align="center" valign="middle" style="border-bottom:1px #000 solid;"> 10.5 </td>
    <td align="center" valign="middle" style="border:1px #000 solid; border-width:0px 1px 1px 1px ;"> 44.5 </td>
    <td align="center" valign="middle" style="border-bottom:1px #000 solid;"> 11.5 </td>
    <td align="center" valign="middle" style="border:1px #000 solid; border-width:0px 1px 1px 1px ;">29 </td>
    
  </tr>
  
  <tr>
    <td align="center" valign="middle" style="border-bottom:1px #000 solid;"> 11 </td>
    <td align="center" valign="middle" style="border:1px #000 solid; border-width:0px 1px 1px 1px ;"> 45 </td>
    <td align="center" valign="middle" style="border-bottom:1px #000 solid;"> 12 </td>
    <td align="center" valign="middle" style="border:1px #000 solid; border-width:0px 1px 1px 1px ;">29.5 </td>
    
  </tr>
  
  <tr>
    <td align="center" valign="middle" style="border-bottom:1px #000 solid;"> 11.5 </td>
    <td align="center" valign="middle" style="border:1px #000 solid; border-width:0px 1px 1px 1px ;"> 45.5 </td>
    <td align="center" valign="middle" style="border-bottom:1px #000 solid;"> 12.5 </td>
    <td align="center" valign="middle" style="border:1px #000 solid; border-width:0px 1px 1px 1px ;">30 </td>
    
  </tr>
  
  <tr>
    <td align="center" valign="middle" style="border-bottom:1px #000 solid;"> 12 </td>
    <td align="center" valign="middle" style="border:1px #000 solid; border-width:0px 1px 1px 1px ;"> 46 </td>
    <td align="center" valign="middle" style="border-bottom:1px #000 solid;"> 13 </td>
    <td align="center" valign="middle" style="border:1px #000 solid; border-width:0px 1px 1px 1px ;">30.5 </td>
    
  </tr>
  
  <tr>
    <td align="center" valign="middle" style="border-bottom:1px #000 solid;"> 12.5 </td>
    <td align="center" valign="middle" style="border:1px #000 solid; border-width:0px 1px 1px 1px ;"> 46.5 </td>
    <td align="center" valign="middle" style="border-bottom:1px #000 solid;"> 13.5 </td>
    <td align="center" valign="middle" style="border:1px #000 solid; border-width:0px 1px 1px 1px ;">31 </td>
    
  </tr>
  
  <tr>
    <td align="center" valign="middle" style="border-bottom:1px #000 solid;"> 13 </td>
    <td align="center" valign="middle" style="border:1px #000 solid; border-width:0px 1px 1px 1px ;"> 47 </td>
    <td align="center" valign="middle" style="border-bottom:1px #000 solid;"> 14 </td>
    <td align="center" valign="middle" style="border:1px #000 solid; border-width:0px 1px 1px 1px ;">31.5 </td>
    
  </tr>
  
  
  <tr>
    <td align="center" valign="middle" style="border-bottom:1px #000 solid;"> 13.5 </td>
    <td align="center" valign="middle" style="border:1px #000 solid; border-width:0px 1px 1px 1px ;"> 47.5 </td>
    <td align="center" valign="middle" style="border-bottom:1px #000 solid;"> 14.5 </td>
    <td align="center" valign="middle" style="border:1px #000 solid; border-width:0px 1px 1px 1px ;">32 </td>
    
  </tr>
  
  <tr>
    <td align="center" valign="middle" style="border-bottom:1px #000 solid;"> 14 </td>
    <td align="center" valign="middle" style="border:1px #000 solid; border-width:0px 1px 1px 1px ;"> 48 </td>
    <td align="center" valign="middle" style="border-bottom:1px #000 solid;"> 15 </td>
    <td align="center" valign="middle" style="border:1px #000 solid; border-width:0px 1px 1px 1px ;">32.5 </td>
    
  </tr>
  
  
      </table>
    -->
    
    
    
    </div>
  </div>
</div>