<style>
@import url('https://fonts.googleapis.com/css2?family=Prata&display=swap');
body {
	margin: 0;
	padding:0px;
	color: #000;
	background: #fff;
}
 
.container22 {
	width: 100%;
}
#mms table { text-align:center;
	margin: 0;
	border-collapse: collapse;
}
#mms td, th {
	padding:5px 8px;  
	border: 1px solid #999;
}
#mms .table-container-outer {
	position: relative;
}
#mms .table-container {
	width: 100%;
	overflow-y: auto;
	_overflow: auto;
	margin: 0px;
}
#mms .table-container::-webkit-scrollbar {
 -webkit-appearance: none;
 width: 14px;
 height: 14px;
}
#mms .table-container::-webkit-scrollbar-thumb {
 border-radius: 0px;
 border: 1px solid #fff;
 background-color: rgba(0, 0, 0, .3);
}
#mms.table-container-fade {
	position: absolute;
	right: 0;
	width: 30px;
	height: 100%;
	background-image: -webkit-linear-gradient(0deg, rgba(255, 255, 255, .5), #fff);
	background-image: -moz-linear-gradient(0deg, rgba(255, 255, 255, .5), #fff);
	background-image: -ms-linear-gradient(0deg, rgba(255, 255, 255, .5), #fff);
	background-image: -o-linear-gradient(0deg, rgba(255, 255, 255, .5), #fff);
	background-image: linear-gradient(0deg, rgba(255, 255, 255, .5), #fff);
}
.table_titles{ padding-top:20px; border-top:2px #000 solid;}
 .table_titles h2{font-family: 'Prata', serif; font-size: 20px;
padding-bottom: 8px;}
 .table_titles p{  serif; font-size:17px;}
@media only screen and (max-width: 600px) {
	.table_titles{ text-align:center;}
	
}
</style>

<div id="mms" class="container22">
	<div class="table_titles">
    <h2>Women's Size Chart</h2>
  </div>
  <div class="table-container-outer">
    <div class="table-container-fade"></div>
    <div class="table-container">
      <table>
        <tbody><tr>
          <td style="background:#eee !important;">Size</td>
          <th>UK (inches)</th>
          <th>Bust (inches)</th>
          <th>Waist (inches)</th>
          <th>Hip (inches)</th>
        </tr>
        <tr>
          <td style="background:#eee;">XS</td>
          <td>4</td>
          <td>32</td>
          <td>26</td>
          <td>36</td>
        </tr>
        <tr>
          <td style="background:#eee;">S</td>
          <td>6</td>
          <td>34</td>
          <td>28</td>
          <td>38</td>
        </tr>
        <tr>
          <td style="background:#eee;">M</td>
          <td>8</td>
          <td>36</td>
          <td>30</td>
          <td>40</td>
        </tr>
        <tr>
          <td style="background:#eee;">L</td>
          <td>10</td>
          <td>38</td>
          <td>32</td>
          <td>42</td>
        </tr>
        <tr>
          <td style="background:#eee;">XL</td>
          <td>12</td>
          <td>40</td>
          <td>34</td>
          <td>44</td>
        </tr>
        <tr>
          <td style="background:#eee;">XXL</td>
          <td>14</td>
          <td>42</td>
          <td>36</td>
          <td>46</td>
        </tr>
        <tr>
          <td style="background:#eee;">3XL</td>
          <td>16</td>
          <td>44</td>
          <td>38</td>
          <td>48</td>
        </tr>
        <tr>
          <td style="background:#eee;">4XL</td>
          <td>18</td>
          <td>46</td>
          <td>40</td>
          <td>50</td>
        </tr>
        <tr>
          <td style="background:#eee;">5XL</td>
          <td>20</td>
          <td>48</td>
          <td>42</td>
          <td>52</td>
        </tr>
        <tr>
          <td style="background:#eee;">6XL</td>
          <td>22</td>
          <td>50</td>
          <td>44</td>
          <td>54</td> 
        </tr>
        <tr>
          <td colspan="5">Please note: This is a standard size guide for the basic body measurements. Lengths & ease will vary according to the outfit style. There may also be variations in some brands commonly with Indian clothing, so please refer to the body measurements displayed on the product page. Alternatively, you may contact our customer care for specific queries at customercare@aashniandco.com</td>
        </tr>
      </tbody></table>
    </div>
  </div>
</div>