<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// phpcs:disable Magento2.Templates.ThisInTemplate.FoundThis

/**
 * Product description template
 *
 * @var $block \Magento\Catalog\Block\Product\View\Description
 */
?>
<div>
<?= /* @noEscape */ $this->helper(Magento\Catalog\Helper\Output::class)->productAttribute(
    $block->getProduct(),
    $block->getProduct()->getDescription(),
    'description'
) ?>
</div>
<h5>Disclaimer: </h5>
<div><?php echo $block->getProduct()->getData('disclaimer'); ?></div>
<h5>Delivery:</h5>
<div><?php echo $block->getProduct()->getData('delivery'); ?></div>



