<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
?>

<?php
/** @var $block \Magento\ConfigurableProduct\Block\Product\View\Type\Configurable*/
$_product    = $block->getProduct();
$_attributes = $block->decorateArray($block->getAllowAttributes());
// error_log($_product->isSaleable()."----gi");
// error_log($_product->getId()."----gi");
// error_log($_product->getTypeId()."----gi");
// error_log(count($_attributes)."---gi");
?>
<?php if ($_product->isSaleable() && count($_attributes))  ://error_log("in if gi");?>
    <?php foreach ($_attributes as $_attribute) : //error_log("in for each gi");?>
        <div class="field configurable required">
            <label class="label" for="attribute<?= $block->escapeHtmlAttr($_attribute->getAttributeId()) ?>">
                <span><?= $block->escapeHtml($_attribute->getProductAttribute()->getStoreLabel()) ?></span>
            </label>
            <div class="control size-select-radio">
                <div class="mage_error_size_select" style="display: none;">This is a required field.</div>
                <select name="super_attribute[<?= $block->escapeHtmlAttr($_attribute->getAttributeId()) ?>]"
                        data-selector="super_attribute[<?= $block->escapeHtmlAttr($_attribute->getAttributeId()) ?>]"
                        data-validate="{required:true}"
                        id="attribute<?= $block->escapeHtmlAttr($_attribute->getAttributeId()) ?>"
                        class="super-attribute-select">
                    <option value=""><?= $block->escapeHtml(__('Choose an Option...')) ?></option>
                </select>
                
                <!-- custom code for buttons -->
                <div class="super-attribute-select-btn-grp" id="btn-attribute<?= $block->escapeHtmlAttr($_attribute->getAttributeId()) ?>">
                </div>
                <!-- <div class="tooltip pdp-size-tooltip"></div> -->
                <!-- end custom code -->
            </div>
        </div>
    <?php endforeach; ?>
    <script type="text/x-magento-init">
        {
            "#product_addtocart_form": {
                "configurable": {
                    "spConfig": <?= /* @noEscape */ $block->getJsonConfig() ?>,
                    "gallerySwitchStrategy": "<?= $block->escapeJs($block->getVar(
                        'gallery_switch_strategy',
                        'Magento_ConfigurableProduct'
                    ) ?: 'replace'); ?>"
                }
            },
            "*" : {
                "Magento_ConfigurableProduct/js/catalog-add-to-cart": {}
            }
        }
    </script>
<?php endif;?>
<script>
    require(['jquery'], function ($) {
        $('body').on('click', '#product-addtocart-button', function() {
            var errDiv = $('.mage_error_size_select');
            errDiv.hide();
            var dropdownVal = $('.super-attribute-select').val();
            var mage_error = $('<div class="mage_error_size_select">This is a required field.</div>')
            if(dropdownVal == '' || dropdownVal == null || dropdownVal == undefined){
                errDiv.show();
            }
        });
    });
</script>